#!/usr/bin/env python3
"""Generate tmp/research/*.json with P0 product data for build.py merge."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tmp" / "research"
VER = "2026-06"


def src(url: str, title: str = "") -> dict:
    return {"url": url, "title": title or url, "accessed": VER}


def p(
    id: str, name_zh: str, name_en: str, vendor_id: str,
    l1: str, l2: str, origin: str, kernel: str,
    maturity: str, loc: str, pricing: str, conf: float,
    strengths_zh: list, strengths_en: list,
    limitations_zh: list, limitations_en: list,
    industries: list, url: str,
    benchmarks: list | None = None, ticker: str | None = None,
    breakthroughs: list | None = None,
) -> dict:
    d = {
        "id": id, "name_zh": name_zh, "name_en": name_en, "vendor_id": vendor_id,
        "category_l1": l1, "category_l2": l2, "origin": origin, "kernel": kernel,
        "maturity": maturity, "localization_depth": loc,
        "strengths_zh": strengths_zh, "strengths_en": strengths_en,
        "limitations_zh": limitations_zh, "limitations_en": limitations_en,
        "industries": industries, "pricing": pricing, "confidence": conf,
        "last_verified": VER, "sources": [src(url, name_en)],
    }
    if benchmarks:
        d["international_benchmarks"] = benchmarks
    if ticker:
        d["listed_ticker"] = ticker
    if breakthroughs:
        d["breakthroughs"] = breakthroughs
    return d


L1_RD = "研发设计"
L1_MFG = "生产制造"
L1_BIZ = "经营管理"
L1_PLAT = "基础平台"


def eda_products() -> list[dict]:
    return [
        p("empyrean-alextool", "华大九天 Aether", "Empyrean Aether", "empyrean", L1_RD, "EDA", "domestic", "自主", "high", "partial", "high", 0.88,
          ["模拟全流程覆盖", "国内晶圆厂验证案例增多"], ["Full custom analog flow", "Growing foundry validation in China"],
          ["先进制程数字后端仍弱于国际三巨头", "IP生态与海外EDA仍有差距"], ["Digital backend for advanced nodes lags big three", "IP ecosystem gap vs global EDA"],
          ["集成电路", "半导体制造"], "https://www.empyrean.com.cn/", ["virtuoso"], "301269.SZ",
          [{"year": 2022, "text_zh": "模拟全流程工具链通过多家国内头部晶圆厂验证", "source_url": "https://www.empyrean.com.cn/"}]),
        p("empyrean-digital", "华大九天 数字后端", "Empyrean Digital Implementation", "empyrean", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "high", 0.82,
          ["布局布线国产化突破", "政策与信创采购推动"], ["Place-and-route localization milestone", "Policy-driven procurement"],
          ["7nm以下竞争力有限", "客户以成熟工艺为主"], ["Limited competitiveness below 7nm", "Customers mostly mature nodes"],
          ["集成电路"], "https://www.empyrean.com.cn/", ["innovus"]),
        p("primarius-device", "概伦器件建模", "Primarius Device Modeling", "primarius", L1_RD, "EDA", "domestic", "自主", "high", "partial", "high", 0.86,
          ["BSIM/器件模型国际认可度高", "与国内Foundry深度合作"], ["BSIM-grade device models", "Deep foundry partnerships"],
          ["系统级与签核工具链不完整"], ["Incomplete signoff and system-level stack"],
          ["集成电路", "半导体"], "https://www.primarius-tech.com/", ["hspice"], "688206.SH"),
        p("semitron-yield", "广立微 WAT/Yield", "Semitron WAT & Yield", "semitron", L1_RD, "EDA", "domestic", "自主", "high", "partial", "high", 0.85,
          ["良率分析与测试芯片设计领先", "科创板上市背书"], ["Leading yield analytics and test chip", "STAR Market listed"],
          ["品类偏制造测试分析非全流程EDA"], ["Focused on yield/test not full-flow EDA"],
          ["半导体制造", "封测"], "https://www.semitron.com/", None, "301095.SZ"),
        p("x-epic-verification", "芯华章 验证平台", "X-Epic Verification", "x-epic", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "high", 0.80,
          ["数字验证与形式化工具国产化", "融资与人才储备强"], ["Digital verification and formal tools", "Strong funding and talent"],
          ["商业化规模仍小于Synopsys/Cadence"], ["Commercial scale below Synopsys/Cadence"],
          ["集成电路", "芯片设计"], "https://www.x-epic.com/", ["vcs"]),
        p("guowei-eda", "国微芯 EDA", "SMIT EDA Tools", "guowei", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "mid", 0.75,
          ["FPGA/原型验证与形式验证", "深圳产业政策支持"], ["FPGA prototyping and formal verification", "Shenzhen policy support"],
          ["产品线较窄", "国际客户少"], ["Narrow product line", "Few international customers"],
          ["集成电路", "FPGA"], "https://www.smit.com.cn/"),
        p("s2c-prototyping", "思尔芯 原型验证", "S2C Prototyping", "s2c", L1_RD, "EDA", "domestic", "自主", "high", "partial", "high", 0.83,
          ["FPGA原型验证国内市占领先", "大芯片验证场景成熟"], ["Leading China FPGA prototyping share", "Mature for large SoC bring-up"],
          ["依赖海外FPGA硬件", "软件生态国际化不足"], ["Depends on foreign FPGA hardware", "Limited global software ecosystem"],
          ["集成电路", "通信", "人工智能"], "https://www.s2ceda.com/", ["synopsys-haps"]),
        p("fangxing-simulation", "九同方 电磁仿真", "FangXing EM Simulation", "fangxing", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "mid", 0.72,
          ["电磁/热仿真国产化", "国防与航天客户"], ["EM/thermal simulation localization", "Defense and aerospace clients"],
          ["民用市场知名度低", "与HFSS仍有差距"], ["Low consumer brand awareness", "Gap vs HFSS"],
          ["航空航天", "电子"], "http://www.fangxing.com/"),
        p("jlceda", "立创EDA", "JLCEDA", "jlc", L1_RD, "EDA", "domestic", "开源", "mid", "partial", "free", 0.78,
          ["免费在线PCB设计", "与立创商城供应链打通"], ["Free online PCB design", "Integrated with JLC supply chain"],
          ["高速/射频设计能力有限", "企业级功能弱于Altium"], ["Limited high-speed/RF", "Weaker enterprise features vs Altium"],
          ["电子制造", "创客", "教育"], "https://lceda.cn/", ["altium-designer"], None,
          [{"year": 2020, "text_zh": "嘉立创推出国产在线EDA并免费开放", "source_url": "https://lceda.cn/"}]),
        p("orcafoundry-pdk", "芯华章 Orca 形式验证", "X-Epic Formal Verification", "x-epic", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "high", 0.78,
          ["形式验证与等价性检查", "国内主机厂导入试点"], ["Formal and equivalence checking", "OEM pilot deployments"],
          ["工具成熟度仍在迭代", "需要更多PDK适配"], ["Tool maturity still iterating", "Needs more PDK ports"],
          ["汽车电子", "集成电路"], "https://www.x-epic.com/"),
        p("hongxin-eda", "鸿芯微纳 布局布线", "Hongxin Nano Place & Route", "hongxin", L1_RD, "EDA", "domestic", "自主", "mid", "pilot", "high", 0.76,
          ["数字IC P&R国产化", "杭州EDA产业集群"], ["Digital IC P&R localization", "Hangzhou EDA cluster"],
          ["先进节点案例公开较少", "生态工具链待完善"], ["Few public advanced-node cases", "Ecosystem incomplete"],
          ["集成电路"], "https://www.hongxintech.com/"),
        p("synopsys-design", "Synopsys Design Compiler", "Synopsys Design Compiler", "synopsys", L1_RD, "EDA", "international", "自主", "mission_critical", "core", "high", 0.92,
          ["全球数字综合标准工具", "先进工艺PDK覆盖最全"], ["De-facto global synthesis standard", "Broadest advanced PDK coverage"],
          ["出口管制与合规风险", "价格与授权成本高"], ["Export control and compliance risk", "High license cost"],
          ["集成电路", "汽车电子", "通信"], "https://www.synopsys.com/", None, "SNPS"),
        p("cadence-virtuoso", "Cadence Virtuoso", "Cadence Virtuoso", "cadence", L1_RD, "EDA", "international", "自主", "mission_critical", "core", "high", 0.93,
          ["模拟/混合信号设计事实标准", "与中国头部设计公司深度绑定"], ["Analog/mixed-signal de-facto standard", "Deep ties with China design houses"],
          ["国产化替代阻力大", "订阅与维护费用昂贵"], ["Hard to displace in China", "Expensive subscription"],
          ["集成电路", "半导体"], "https://www.cadence.com/", None, "CDNS"),
        p("siemens-calibre", "Siemens Calibre", "Siemens Calibre DRC/LVS", "siemens-eda", L1_RD, "EDA", "international", "自主", "mission_critical", "core", "high", 0.90,
          ["签核与物理验证市占领先", "先进工艺规则成熟"], ["Leading signoff market share", "Mature advanced node decks"],
          ["政治与供应链不确定性", "本地化支持成本"], ["Geopolitical supply uncertainty", "Localization support cost"],
          ["集成电路", "半导体制造"], "https://eda.sw.siemens.com/"),
        p("keysight-ads", "Keysight ADS", "Keysight ADS", "keysight", L1_RD, "EDA", "international", "自主", "high", "partial", "high", 0.88,
          ["射频微波仿真标杆", "5G/毫米波生态完善"], ["RF/microwave simulation benchmark", "Strong 5G/mmWave ecosystem"],
          ["国产化替代进展慢", "高端模块授权贵"], ["Slow localization displacement", "Premium module pricing"],
          ["通信", "航空航天", "汽车电子"], "https://www.keysight.com/"),
        p("altium-designer", "Altium Designer", "Altium Designer", "altium", L1_RD, "EDA", "international", "自主", "high", "partial", "high", 0.87,
          ["PCB设计用户体验好", "中小企业广泛使用"], ["Strong PCB UX", "Widely used by SMEs"],
          ["高端封装与仿真弱于Cadence", "云协同对中国合规考量"], ["Weaker advanced packaging vs Cadence", "Cloud compliance considerations"],
          ["电子", "消费电子", "工业"], "https://www.altium.com/"),
        p("silvaco-tcad", "Silvaco TCAD", "Silvaco TCAD", "silvaco", L1_RD, "EDA", "international", "自主", "high", "pilot", "high", 0.84,
          ["工艺器件仿真TCAD成熟", "教学与研发常用"], ["Mature TCAD for process/device", "Common in academia and R&D"],
          ["国内替代如华大/概伦在追赶", "授权模式传统"], ["Domestic alternatives catching up", "Traditional licensing"],
          ["半导体", "科研"], "https://silvaco.com/"),
        p("mentor-pads", "Siemens PADS", "Siemens PADS", "siemens-eda", L1_RD, "EDA", "international", "自主", "high", "partial", "mid", 0.85,
          ["中端PCB市场占有率高", "与Mentor生态集成"], ["Strong mid-tier PCB share", "Mentor ecosystem integration"],
          ["向Xpedition迁移压力", "云原生能力一般"], ["Migration pressure to Xpedition", "Average cloud-native story"],
          ["电子制造", "工业"], "https://eda.sw.siemens.com/"),
    ]


def cad_products() -> list[dict]:
    return [
        p("zwcad", "中望CAD", "ZWCAD", "zwcad", L1_RD, "CAD", "domestic", "自主", "high", "partial", "mid", 0.90,
          ["2D/3D MCAD国产化龙头", "DWG兼容与信创适配"], ["Leading domestic MCAD", "DWG compatibility and IT innovation lists"],
          ["高端曲面与大型装配弱于CATIA/NX", "海外渠道仍在拓展"], ["Weaker advanced surfacing vs CATIA/NX", "Global channel still expanding"],
          ["机械", "建筑", "模具"], "https://www.zwsoft.cn/", ["autocad"], "300624.SZ"),
        p("gstarcad", "浩辰CAD", "GstarCAD", "gstarcad", L1_RD, "CAD", "domestic", "自主", "high", "partial", "mid", 0.88,
          ["2D CAD海外收入占比高", "移动端与云CAD布局"], ["Strong overseas 2D revenue", "Mobile and cloud CAD"],
          ["3D能力弱于中望", "高端制造业渗透有限"], ["Weaker 3D than ZWSOFT", "Limited high-end manufacturing penetration"],
          ["建筑", "机械", "测绘"], "https://www.gstarcad.com/", ["autocad"], "688657.SH"),
        p("crowncad", "皇冠CAD", "CrownCAD", "hoteam", L1_RD, "CAD", "domestic", "自主", "mid", "pilot", "mid", 0.82,
          ["云原生三维CAD", "协同设计差异化"], ["Cloud-native 3D CAD", "Collaborative design differentiation"],
          ["生态与插件少于SolidWorks", "大客户案例仍在积累"], ["Smaller ecosystem than SolidWorks", "Enterprise references still building"],
          ["机械", "装备"], "https://www.crowncad.com/", ["onshape"]),
        p("caxa-cad", "CAXA CAD", "CAXA CAD", "caxa", L1_RD, "CAD", "domestic", "自主", "high", "partial", "mid", 0.86,
          ["国产CAD老牌厂商", "军工与航天客户基础厚"], ["Long-standing domestic CAD vendor", "Strong defense/aerospace base"],
          ["界面与第三方生态老化", "云转型较慢"], ["Aging UX and third-party ecosystem", "Slower cloud transition"],
          ["航空航天", "机械", "教育"], "https://www.caxa.com/", ["autocad"]),
        p("caxa-3d", "CAXA 3D实体设计", "CAXA 3D Solid Design", "caxa", L1_RD, "CAD", "domestic", "自主", "mid", "partial", "mid", 0.80,
          ["中端三维机械设计", "与CAXA PLM集成"], ["Mid-tier 3D mechanical design", "Integrated with CAXA PLM"],
          ["复杂曲面与仿真联动弱", "市占低于国际巨头"], ["Weak complex surfacing and simulation tie-in", "Share below global leaders"],
          ["机械", "教育"], "https://www.caxa.com/"),
        p("hoteam-cad", "华天CAD", "Hoteam CAD", "hoteam", L1_RD, "CAD", "domestic", "自主", "mid", "pilot", "mid", 0.78,
          ["与华天PLM一体化", "山东工业客户群"], ["Integrated with Hoteam PLM", "Shandong industrial customer base"],
          ["全国品牌声量小于中望浩辰", "3D成熟度中等"], ["Lower national brand than ZW/Gstar", "Mid-tier 3D maturity"],
          ["机械", "汽车零部件"], "https://www.hoteamsoft.com/"),
        p("tianhe-cad", "天河CAD", "THSOFT CAD", "tianhe", L1_RD, "CAD", "domestic", "自主", "mid", "pilot", "mid", 0.74,
          ["装备制造行业定制", "二维图纸积累深"], ["Equipment industry customization", "Deep 2D drawing legacy"],
          ["产品现代化程度一般", "营销覆盖有限"], ["Average product modernization", "Limited marketing reach"],
          ["装备制造", "能源"], "http://www.thsoft.com.cn/"),
        p("pengye-cad", "鹏业CAD", "Pengye CAD", "pengye", L1_RD, "CAD", "domestic", "自主", "mid", "pilot", "low", 0.70,
          ["市政与管网行业CAD", "造价与算量联动"], ["Municipal and pipeline CAD", "Cost estimation integration"],
          ["通用机械CAD竞争力弱", "地域性较强"], ["Weak general MCAD competitiveness", "Regional focus"],
          ["市政", "管网", "建筑"], "http://www.pengyesoftware.com/"),
        p("autocad", "AutoCAD", "AutoCAD", "autodesk", L1_RD, "CAD", "international", "自主", "mission_critical", "core", "high", 0.94,
          ["2D/3D通用设计事实标准", "中国区用户基数巨大"], ["De-facto general design standard", "Huge China user base"],
          ["订阅制成本上升", "国产化替代政策压力"], ["Rising subscription cost", "Localization policy pressure"],
          ["建筑", "机械", "基础设施"], "https://www.autodesk.com.cn/", None, "ADSK"),
        p("solidworks", "SOLIDWORKS", "SOLIDWORKS", "dassault", L1_RD, "CAD", "international", "Parasolid授权", "mission_critical", "core", "high", 0.93,
          ["中小企业三维CAD首选", "仿真与PDM生态丰富"], ["SME 3D CAD default choice", "Rich simulation and PDM ecosystem"],
          ["高端大装配弱于NX/CATIA", "云版本推进慢"], ["Weaker large assembly vs NX/CATIA", "Slow cloud cadence"],
          ["机械", "消费电子", "医疗器械"], "https://www.solidworks.com/"),
        p("catia", "CATIA", "CATIA", "dassault", L1_RD, "CAD", "international", "自主", "mission_critical", "core", "high", 0.92,
          ["航空航天与汽车曲面标杆", "与ENOVIA深度集成"], ["Aerospace/auto surfacing benchmark", "Deep ENOVIA integration"],
          ["学习曲线陡峭", "许可成本极高"], ["Steep learning curve", "Very high license cost"],
          ["汽车", "航空航天", "船舶"], "https://www.3ds.com/products/catia"),
        p("siemens-nx", "Siemens NX", "Siemens NX", "siemens-digital", L1_RD, "CAD", "international", "Parasolid授权", "mission_critical", "core", "high", 0.92,
          ["高端集成CAD/CAM/CAE", "大型装配与多学科优化"], ["High-end integrated CAD/CAM/CAE", "Large assembly and MDO"],
          ["实施与维护复杂", "对本土中小企业过重"], ["Complex implementation", "Heavy for local SMEs"],
          ["汽车", "航空航天", "重工"], "https://plm.sw.siemens.com/"),
        p("creo", "Creo Parametric", "Creo Parametric", "ptc", L1_RD, "CAD", "international", "自主", "high", "partial", "high", 0.90,
          ["参数化设计历史悠久", "Windchill PLM协同"], ["Long parametric history", "Windchill PLM synergy"],
          ["用户体验落后于新竞品", "云原生能力有限"], ["UX behind newer rivals", "Limited cloud-native"],
          ["机械", "电子", "工业"], "https://www.ptc.com/en/products/creo"),
        p("inventor", "Autodesk Inventor", "Autodesk Inventor", "autodesk", L1_RD, "CAD", "international", "自主", "high", "partial", "mid", 0.88,
          ["中端机械三维CAD", "与Vault/ Fusion衔接"], ["Mid-tier mechanical 3D", "Vault and Fusion bridge"],
          ["高端市场被SolidWorks/NX挤压", "发展重心转向Fusion"], ["Squeezed at high end", "Focus shifting to Fusion"],
          ["机械", "建筑设备"], "https://www.autodesk.com/products/inventor"),
        p("fusion360", "Fusion 360", "Fusion 360", "autodesk", L1_RD, "CAD", "international", "自主", "high", "partial", "low", 0.87,
          ["云原生CAD/CAM一体", "创客与初创友好"], ["Cloud-native CAD/CAM", "Maker and startup friendly"],
          ["企业级数据治理弱", "国内云访问稳定性问题"], ["Weak enterprise data governance", "China cloud access variability"],
          ["教育", "创客", "中小企业"], "https://www.autodesk.com/products/fusion-360"),
        p("onshape", "Onshape", "Onshape", "ptc", L1_RD, "CAD", "international", "自主", "mid", "pilot", "mid", 0.85,
          ["纯浏览器CAD", "版本管理与协作先进"], ["Browser-only CAD", "Advanced versioning and collaboration"],
          ["国内采用率低于SolidWorks", "高级曲面能力有限"], ["Lower China adoption than SW", "Limited advanced surfacing"],
          ["机械", "教育"], "https://www.onshape.com/"),
        p("bricscad", "BricsCAD", "BricsCAD", "bricsys", L1_RD, "CAD", "international", "自主", "high", "partial", "mid", 0.84,
          ["DWG平台兼容性强", "一次性授权选项"], ["Strong DWG platform", "Perpetual license option"],
          ["国内渠道与生态较小", "三维市场声量低"], ["Smaller China channel", "Lower 3D mindshare"],
          ["建筑", "机械"], "https://www.bricsys.com/"),
        p("sketchup", "SketchUp", "SketchUp", "trimble", L1_RD, "CAD", "international", "自主", "high", "partial", "low", 0.86,
          ["建筑概念设计流行", "上手快生态插件多"], ["Popular conceptual BIM", "Easy learning curve and plugins"],
          ["精密机械设计不适用", "BIM深度不足"], ["Not for precision MCAD", "Shallow BIM depth"],
          ["建筑", "室内设计", "景观"], "https://www.sketchup.com/"),
        p("freecad", "FreeCAD", "FreeCAD", "freecad", L1_RD, "CAD", "open_source", "开源", "mid", "pilot", "free", 0.80,
          ["开源参数化CAD", "社区活跃可定制"], ["Open-source parametric CAD", "Active community"],
          ["企业支持弱", "稳定性与性能参差"], ["Weak enterprise support", "Variable stability/performance"],
          ["教育", "创客", "机械"], "https://www.freecad.org/", ["solidworks"]),
        p("librecad", "LibreCAD", "LibreCAD", "librecad", L1_RD, "CAD", "open_source", "LibreCAD RS_Entity + libdxfrw", "mid", "pilot", "free", 0.75,
          ["GPL开源2D CAD（QCAD CE传承）", "RS_Entity图元+libdxfrw DXF/DWG"], ["GPL 2D CAD (QCAD CE lineage)", "RS_Entity + libdxfrw DXF/DWG"],
          ["无B-rep实体建模", "功能远少于商业DWG平台"], ["No B-rep solid modeling", "Far fewer features than commercial DWG platforms"],
          ["教育", "测绘"], "https://librecad.org/"),
    ]


def cae_products() -> list[dict]:
    return [
        p("pera-sim", "PERA SIM", "PERA SIM", "pera", L1_RD, "CAE", "domestic", "自主", "high", "partial", "high", 0.85,
          ["多物理场仿真平台", "国防与航空航天案例"], ["Multiphysics simulation platform", "Defense and aerospace cases"],
          ["汽车主机厂核心仍多用Ansys", "国际学术引用少"], ["OEM core still often Ansys", "Limited international citations"],
          ["航空航天", "汽车", "能源"], "https://www.peraglobal.com/", ["ansys-mechanical"]),
        p("suochen-abyss", "索辰 Abyss", "Suochen Abyss", "suochen", L1_RD, "CAE", "domestic", "自主", "mid", "pilot", "high", 0.82,
          ["国产CAE科创板代表", "流体与结构求解器自研"], ["STAR Market CAE representative", "In-house CFD/structural solvers"],
          ["商业化规模仍小", "生态与培训体系建设中"], ["Small commercial scale", "Ecosystem and training building"],
          ["航空航天", "船舶", "能源"], "https://www.suochen.com.cn/", ["ansys-fluent"], "688507.SH"),
        p("bochu-cypcut", "柏楚 CypCut", "Bochu CypCut", "bochu", L1_MFG, "CAM", "domestic", "自主", "mission_critical", "core", "high", 0.90,
          ["激光切割控制系统市占领先", "与激光器厂商深度绑定"], ["Leading laser cutting control share", "Deep laser OEM partnerships"],
          ["品类聚焦激光切割", "国际拓展早期"], ["Focused on laser cutting", "Early international expansion"],
          ["激光加工", "金属加工"], "https://www.bochu.com/", ["mastercam"], "688188.SH"),
        p("weihong-nc", "维宏数控", "Weihong NC", "weihong", L1_MFG, "CAM", "domestic", "自主", "high", "core", "mid", 0.88,
          ["雕刻/加工中心数控系统", "性价比与本土化服务"], ["Engraving/machining center CNC", "Value and local service"],
          ["高端五轴与精度仍追赶", "品牌溢价有限"], ["Chasing high-end 5-axis precision", "Limited brand premium"],
          ["木工", "金属加工", "广告"], "https://www.weihong.com.cn/", ["fanuc-cnc"], "300508.SZ"),
        p("huazhong-cnc", "华中数控", "Huazhong CNC", "huazhong", L1_MFG, "CAM", "domestic", "自主", "high", "partial", "mid", 0.86,
          ["国产数控系统国家队", "航空航天示范应用"], ["National CNC system champion", "Aerospace demonstration"],
          ["民用市场竞争激烈", "生态与刀具库需加强"], ["Fierce civilian competition", "Needs stronger tooling ecosystem"],
          ["航空航天", "汽车", "机床"], "http://www.huazhongcnc.com/", ["siemens-sinumerik"], "300161.SZ"),
        p("gsk-cnc", "广数数控", "GSK CNC", "gsk", L1_MFG, "CAM", "domestic", "自主", "high", "partial", "mid", 0.84,
          ["经济型数控系统市占高", "机床厂商配套广泛"], ["High share in economy CNC", "Wide machine tool OEM pairing"],
          ["高端多轴能力有限", "软件体验待提升"], ["Limited high-end multi-axis", "Software UX needs work"],
          ["机床", "模具"], "http://www.gsk.com.cn/"),
        p("shifeng-simulation", "十沣科技 SimRight", "SimRight CAE Cloud", "shifeng", L1_RD, "CAE", "domestic", "自主", "mid", "pilot", "mid", 0.76,
          ["云原生CAE前后处理", "与开源求解器结合"], ["Cloud-native CAE pre/post", "Pairs with open solvers"],
          ["求解器自研仍在早期", "大客户案例有限"], ["Early in-house solvers", "Limited enterprise references"],
          ["汽车", "机械"], "https://www.simright.com/"),
        p("ansys-mechanical", "Ansys Mechanical", "Ansys Mechanical", "ansys", L1_RD, "CAE", "international", "自主", "mission_critical", "core", "high", 0.93,
          ["结构仿真事实标准", "与中国车企深度合作"], ["Structural simulation standard", "Deep China automotive partnerships"],
          ["许可昂贵", "云化与数据合规挑战"], ["Expensive licensing", "Cloud and data compliance challenges"],
          ["汽车", "航空航天", "电子"], "https://www.ansys.com/", None, "ANSS"),
        p("ansys-fluent", "Ansys Fluent", "Ansys Fluent", "ansys", L1_RD, "CAE", "international", "自主", "mission_critical", "core", "high", 0.92,
          ["CFD行业标杆", "涡轮与汽车热管理广泛应用"], ["CFD industry benchmark", "Wide turbo and automotive thermal use"],
          ["对国产求解器替代形成壁垒", "高性能计算成本高"], ["Barrier to domestic solvers", "High HPC cost"],
          ["汽车", "能源", "航空航天"], "https://www.ansys.com/products/fluids/ansys-fluent"),
        p("abaqus", "Abaqus", "Abaqus", "dassault", L1_RD, "CAE", "international", "自主", "mission_critical", "core", "high", 0.91,
          ["非线性结构仿真强项", "与CATIA工作流集成"], ["Nonlinear structural strength", "CATIA workflow integration"],
          ["价格与求解器封闭", "国内云求解供应少"], ["Price and closed solver", "Limited domestic cloud solving"],
          ["汽车", "轨道交通", "消费电子"], "https://www.3ds.com/products/simulia/abaqus"),
        p("altair-hyperworks", "Altair HyperWorks", "Altair HyperWorks", "altair", L1_RD, "CAE", "international", "自主", "high", "partial", "high", 0.89,
          ["多学科优化与轻量化", "许可单元模式灵活"], ["MDO and lightweighting", "Flexible unit licensing"],
          ["国内品牌认知低于Ansys", "部分模块学习曲线陡"], ["Lower China mindshare than Ansys", "Steep modules learning curve"],
          ["汽车", "航空航天"], "https://altair.com/hyperworks", None, "ALTR"),
        p("comsol", "COMSOL Multiphysics", "COMSOL Multiphysics", "comsol", L1_RD, "CAE", "international", "自主", "high", "partial", "high", 0.88,
          ["多物理场耦合仿真", "科研与新兴产业常用"], ["Multiphysics coupling", "Common in research and emerging industries"],
          ["大规模工业级求解性能受限", "本地化销售团队小"], ["Limited large industrial HPC", "Small local sales team"],
          ["新能源", "半导体", "医疗"], "https://www.comsol.com/"),
        p("msc-nastran", "MSC Nastran", "MSC Nastran", "hexagon", L1_RD, "CAE", "international", "自主", "high", "partial", "high", 0.87,
          ["航空航天线性结构经典求解器", "Nastran格式行业标准"], ["Classic aerospace linear solver", "Nastran format standard"],
          ["产品组合分散在Hexagon", "创新节奏受并购影响"], ["Portfolio scattered under Hexagon", "Innovation pace affected by M&A"],
          ["航空航天", "汽车"], "https://hexagon.com/products/msc-nastran"),
        p("mastercam", "Mastercam", "Mastercam", "mastercam", L1_MFG, "CAM", "international", "自主", "mission_critical", "core", "high", 0.90,
          ["数控编程市占领先", "多轴加工策略成熟"], ["Leading CAM programming share", "Mature multi-axis strategies"],
          ["云协同弱", "对国产数控 post 支持参差"], ["Weak cloud collaboration", "Variable post support for domestic CNC"],
          ["模具", "航空航天", "医疗"], "https://www.mastercam.com/"),
        p("powermill", "PowerMill", "PowerMill", "autodesk", L1_MFG, "CAM", "international", "自主", "high", "partial", "high", 0.88,
          ["模具与五轴加工强项", "与Fusion/Delcam传承"], ["Mold and 5-axis strength", "Delcam heritage"],
          ["并入Autodesk后授权变化", "本土竞品在激光切割领先"], ["License changes under Autodesk", "Domestic rivals lead laser cutting"],
          ["模具", "航空航天"], "https://www.autodesk.com/products/powermill"),
        p("hypermill", "hyperMILL", "hyperMILL", "openmind", L1_MFG, "CAM", "international", "自主", "high", "partial", "high", 0.86,
          ["五轴联动策略先进", "汽车与精密模具"], ["Advanced 5-axis strategies", "Automotive and precision molds"],
          ["价格高昂", "国内培训资源有限"], ["High price", "Limited China training"],
          ["模具", "航空航天", "医疗"], "https://www.openmind-tech.com/"),
        p("cimatron", "Cimatron", "Cimatron", "cimatron", L1_MFG, "CAM", "international", "自主", "high", "partial", "high", 0.85,
          ["模具设计制造一体化", "型腔加工策略成熟"], ["Integrated mold design/manufacturing", "Mature cavity strategies"],
          ["市场份额被NX/CATIA挤压", "品牌更新慢"], ["Share squeezed by NX/CATIA", "Slow brand refresh"],
          ["模具", "消费电子"], "https://www.cimatron.com/"),
        p("jiyuan-simulation", "积元仿真", "Jiyuan Simulation", "jiyuan", L1_RD, "CAE", "domestic", "自主", "experimental", "pilot", "mid", 0.65,
          ["电磁与热仿真创业团队", "特定行业定制"], ["EM/thermal startup solvers", "Industry-specific customization"],
          ["公开案例与文档少", "成熟度待验证"], ["Few public cases", "Maturity unproven"],
          ["电子", "新能源"], "https://www.jiyuan-tech.com/"),
    ]


def plm_products() -> list[dict]:
    return [
        p("hoteam-plm", "华天PLM", "Hoteam PLM", "hoteam", L1_RD, "PLM", "domestic", "自主", "high", "partial", "mid", 0.84,
          ["国产PLM老牌", "与CAD/MES衔接"], ["Long-standing domestic PLM", "CAD/MES integration"],
          ["大型集团复杂部署经验少于Teamcenter", "SaaS化程度一般"], ["Fewer mega-enterprise deployments than TC", "Average SaaS maturity"],
          ["机械", "汽车零部件", "军工"], "https://www.hoteamsoft.com/"),
        p("sysware-ipdc", "索为IPDC", "Sysware IPDC", "sysware", L1_RD, "PLM", "domestic", "自主", "mid", "pilot", "high", 0.78,
          ["航空工业背景PLM", "型号研制流程数字化"], ["Aviation-industry PLM heritage", "Program digitalization"],
          ["民用市场推广慢", "产品现代化待加强"], ["Slow commercial market push", "Product modernization needed"],
          ["航空航天", "军工"], "http://www.sysware.com.cn/"),
        p("tongyuan-mworks", "同元MWorks", "Tongyuan MWorks", "tongyuan", L1_RD, "MBSE", "domestic", "自主", "high", "partial", "mid", 0.82,
          ["系统建模与仿真国内领先", "MBSE方法论支撑"], ["Leading domestic SysML modeling", "MBSE methodology support"],
          ["与国际Modelica生态衔接需加强", "汽车行业渗透仍浅"], ["Needs tighter Modelica ecosystem", "Shallow automotive penetration"],
          ["航空航天", "车辆", "能源"], "https://www.tongyuan.cc/"),
        p("yonyou-plm", "用友PLM Cloud", "Yonyou PLM Cloud", "yonyou", L1_RD, "PLM", "domestic", "自主", "mid", "pilot", "mid", 0.80,
          ["与ERP一体化套件", "云原生交付"], ["Integrated with ERP suite", "Cloud-native delivery"],
          ["高端研发场景深度不足", "复杂BOM变更弱于国际PLM"], ["Shallow for advanced R&D", "Weaker complex BOM than global PLM"],
          ["离散制造", "电子"], "https://www.yonyou.com/", ["windchill"]),
        p("kingdee-plm", "金蝶PLM", "Kingdee PLM", "kingdee", L1_RD, "PLM", "domestic", "自主", "mid", "pilot", "mid", 0.78,
          ["中小企业PLM切入", "与星空/苍穹ERP协同"], ["SME PLM entry", "Synergy with Kingdee ERP"],
          ["大型集团可扩展性有限", "MBSE能力基础"], ["Limited mega-group scalability", "Basic MBSE"],
          ["电子", "机械", "消费品"], "https://www.kingdee.com/"),
        p("avic-plm", "神舟软件AVIDM", "AVIC AVIDM", "avic", L1_RD, "PLM", "domestic", "自主", "high", "core", "quote", 0.80,
          ["航空型号研制PLM", "高安全与合规"], ["Aviation program PLM", "High security and compliance"],
          ["行业封闭难复制到民用", "商业授权不透明"], ["Closed vertical hard to replicate commercially", "Opaque commercial licensing"],
          ["航空航天", "军工"], "http://www.avic.com/"),
        p("teamcenter", "Teamcenter", "Teamcenter", "siemens-digital", L1_RD, "PLM", "international", "自主", "mission_critical", "core", "high", 0.92,
          ["大型离散制造PLM标杆", "与NX一体化"], ["Large discrete PLM benchmark", "Integrated with NX"],
          ["实施成本极高", "本地化与数据主权顾虑"], ["Very high implementation cost", "Localization and data sovereignty concerns"],
          ["汽车", "航空航天", "重工"], "https://plm.sw.siemens.com/"),
        p("enovia", "ENOVIA", "ENOVIA", "dassault", L1_RD, "PLM", "international", "自主", "mission_critical", "core", "high", 0.91,
          ["复杂产品协同与合规", "与3DEXPERIENCE一体"], ["Complex product collaboration", "3DEXPERIENCE integrated"],
          ["学习曲线与定制成本高", "对中小企过重"], ["Steep learning and customization", "Heavy for SMEs"],
          ["航空航天", "汽车", "生命科学"], "https://www.3ds.com/products/enovia"),
        p("windchill", "Windchill", "Windchill", "ptc", L1_RD, "PLM", "international", "自主", "high", "partial", "high", 0.90,
          ["参数化产品与变更管理", "与Creo/ThingWorx协同"], ["Parametric product and change mgmt", "Creo/ThingWorx synergy"],
          ["云版本推进慢于竞品", "旧版UI体验参差"], ["Slower cloud than rivals", "Variable legacy UX"],
          ["电子", "工业", "医疗器械"], "https://www.ptc.com/en/products/windchill"),
        p("aras-innovator", "Aras Innovator", "Aras Innovator", "aras", L1_RD, "PLM", "international", "自主", "high", "pilot", "quote", 0.85,
          ["开放架构可定制PLM", "订阅模式灵活"], ["Open customizable PLM architecture", "Flexible subscription"],
          ["国内实施伙伴少", "品牌认知低于三巨头"], ["Few China implementers", "Lower mindshare than big three"],
          ["汽车", "国防", "工业"], "https://www.aras.com/"),
        p("oracle-agile", "Oracle Agile PLM", "Oracle Agile PLM", "oracle", L1_RD, "PLM", "international", "自主", "high", "partial", "high", 0.86,
          ["电子行业PLM与Oracle ERP集成", "合规与质量模块成熟"], ["Electronics PLM with Oracle ERP", "Mature compliance/quality"],
          ["创新节奏慢", "本地支持资源收缩"], ["Slow innovation", "Shrinking local support"],
          ["电子", "医疗", "工业"], "https://www.oracle.com/scm/product-lifecycle-management/"),
        p("shenzhou-mdm", "华望PLM", "Huawang PLM", "huawang", L1_RD, "PLM", "domestic", "自主", "mid", "pilot", "mid", 0.72,
          ["装备制造PLM", "项目型制造"], ["Equipment manufacturing PLM", "Project-based manufacturing"],
          ["市场声量小", "功能深度待验证"], ["Low market visibility", "Depth unverified"],
          ["装备制造", "轨道交通"], "http://www.huawangsoft.com/"),
    ]


def mes_dcs_products() -> list[dict]:
    return [
        p("supcon-supos", "中控SUPOS", "SUPCON SUPOS", "supcon", L1_MFG, "DCS", "domestic", "自主", "mission_critical", "core", "high", 0.91,
          ["流程工业DCS市占第一", "PlantMart工业互联网平台"], ["#1 process DCS share in China", "PlantMart IIoT platform"],
          ["化工以外行业拓展仍在进行", "高端仪表仍部分进口"], ["Expanding beyond chemicals", "Some high-end instruments imported"],
          ["化工", "石化", "冶金"], "https://www.supcon.com/", ["emerson-deltav"], "688777.SH"),
        p("hollysys-dcs", "和利时DCS", "Hollysys DCS", "hollysys", L1_MFG, "DCS", "domestic", "自主", "high", "core", "high", 0.88,
          ["电力与轨道自动化背景", "核电DCS国产化突破"], ["Power and rail automation heritage", "Nuclear DCS localization"],
          ["化工市占低于中控", "国际化有限"], ["Lower chemical share than SUPCON", "Limited internationalization"],
          ["电力", "核电", "化工"], "https://www.hollysys.com/", ["honeywell-experion"], "HOLI"),
        p("nari-dcs", "南瑞DCS/电网自动化", "NARI Power Automation", "nari", L1_MFG, "DCS", "domestic", "自主", "mission_critical", "core", "high", 0.90,
          ["电网调度与变电站自动化龙头", "国网体系深度绑定"], ["Grid dispatch and substation leader", "Deep State Grid ties"],
          ["流程化工DCS非主业", "市场化定价透明度低"], ["Process DCS not core", "Opaque market pricing"],
          ["电力", "电网", "新能源"], "http://www.nari.cn/", ["abb-800xa"], "600406.SH"),
        p("sciyon-dcs", "科远DCS", "SCIYON DCS", "sciyon", L1_MFG, "DCS", "domestic", "自主", "high", "partial", "mid", 0.84,
          ["热电与建材DCS优势", "智慧电厂整体方案"], ["Strength in thermal power DCS", "Smart plant solutions"],
          ["大型石化全厂级案例少", "品牌全国化进行中"], ["Few mega-petrochemical references", "National brand building"],
          ["电力", "建材", "化工"], "https://www.sciyon.com/", ["siemens-pcs7"], "002380.SZ"),
        p("wellintech-kingview", "亚控组态王", "Wellintech KingView", "wellintech", L1_MFG, "SCADA", "domestic", "自主", "high", "partial", "low", 0.86,
          ["国产组态软件老牌", "中小企业SCADA普及"], ["Legacy domestic SCADA/HMI", "Wide SME adoption"],
          ["云原生与安全加固落后", "高端流程行业渗透有限"], ["Behind on cloud-native security", "Limited high-end process penetration"],
          ["市政", "水处理", "制造业"], "https://www.kingview.com/", ["wonderware"]),
        p("emerson-deltav", "Emerson DeltaV", "Emerson DeltaV", "emerson", L1_MFG, "DCS", "international", "自主", "mission_critical", "core", "high", 0.90,
          ["化工石化全球标杆DCS", "中国区服务网络成熟"], ["Global chemical DCS benchmark", "Mature China service network"],
          ["国产化替代在大型炼化推进", "硬件供应链风险"], ["Localization push in mega refineries", "Hardware supply risk"],
          ["石化", "化工", "制药"], "https://www.emerson.com/"),
        p("honeywell-experion", "Honeywell Experion", "Honeywell Experion", "honeywell", L1_MFG, "DCS", "international", "自主", "mission_critical", "core", "high", 0.89,
          ["炼化一体化DCS强项", "与霍尼韦尔仪表协同"], ["Integrated refining DCS strength", "Honeywell instrument synergy"],
          ["价格与备件成本高", "本土人才竞争加剧"], ["High spare parts cost", "Intense local talent competition"],
          ["石化", "化工"], "https://process.honeywell.com/"),
        p("siemens-pcs7", "Siemens PCS 7", "Siemens PCS 7", "siemens-process", L1_MFG, "DCS", "international", "自主", "mission_critical", "core", "high", 0.89,
          ["制药与精细化工常用", "与TIA Portal集成"], ["Common in pharma and fine chemicals", "TIA Portal integration"],
          ["老版本迁移压力大", "国产化政策下份额承压"], ["Legacy migration pressure", "Share pressure under localization policy"],
          ["制药", "化工", "食品"], "https://www.siemens.com/global/en/products/automation/process-control.html"),
        p("abb-800xa", "ABB 800xA", "ABB 800xA", "abb", L1_MFG, "DCS", "international", "自主", "high", "partial", "high", 0.87,
          ["电力与海事自动化", "模块化系统架构"], ["Power and marine automation", "Modular system architecture"],
          ["流程化工在华份额下降", "软件许可模式复杂"], ["Declining process share in China", "Complex licensing"],
          ["电力", "海事", "矿业"], "https://new.abb.com/process-automation"),
        p("yokogawa-centum", "Yokogawa CENTUM", "Yokogawa CENTUM", "yokogawa", L1_MFG, "DCS", "international", "自主", "high", "partial", "high", 0.88,
          ["化工仪表与DCS协同", "可靠性口碑好"], ["Strong instrument and DCS synergy", "Reliability reputation"],
          ["数字化平台弱于欧美竞品", "价格敏感市场承压"], ["Weaker digital platform", "Price-sensitive market pressure"],
          ["化工", "石化"], "https://www.yokogawa.com/"),
        p("baosight-mes", "宝信MES", "Baosight MES", "baosight", L1_MFG, "MES", "domestic", "自主", "mission_critical", "core", "high", 0.90,
          ["钢铁MES绝对龙头", "宝武生态深度绑定"], ["Dominant steel MES", "Deep Baowu ecosystem"],
          ["跨行业复制需定制", "非钢行业案例少于赛意"], ["Cross-industry needs customization", "Fewer non-steel refs than SIE"],
          ["钢铁", "有色", "冶金"], "https://www.baosight.com/", ["siemens-opcenter"], "600845.SH"),
        p("sie-mes", "赛意SMOM", "SIE SMOM", "sie", L1_MFG, "MES", "domestic", "自主", "high", "partial", "mid", 0.85,
          ["离散制造MES与工业互联网", "华为/美的等案例"], ["Discrete MES and IIoT", "Huawei/Midea references"],
          ["流程行业经验少于宝信", "实施交付质量参差"], ["Less process industry depth", "Variable implementation quality"],
          ["电子", "家电", "机械"], "https://www.chinasie.com/", ["siemens-opcenter"], "300687.SZ"),
        p("goodsgather-mes", "谷器数据MES", "GoodsGather MES", "goodsgather", L1_MFG, "MES", "domestic", "自主", "mid", "partial", "mid", 0.80,
          ["汽车零部件MES专注", "云端部署灵活"], ["Automotive parts MES focus", "Flexible cloud deployment"],
          ["规模小于头部MES厂商", "多工厂集团治理弱"], ["Smaller than top MES vendors", "Weak multi-plant governance"],
          ["汽车零部件", "机械"], "https://www.goodsgather.com/"),
        p("cosmoplat-mes", "卡奥斯天智工", "COSMOPlat Tianzhigong", "haier", L1_MFG, "MES", "domestic", "自主", "high", "partial", "mid", 0.83,
          ["海尔大规模定制实践外溢", "跨行业复制进行中"], ["Haier mass customization export", "Cross-industry replication ongoing"],
          ["对外交付仍在成熟化", "与海尔生态绑定印象"], ["External delivery maturing", "Perceived Haier ecosystem tie"],
          ["家电", "服装", "机械"], "https://www.cosmoplat.com/"),
        p("siemens-opcenter", "Siemens Opcenter", "Siemens Opcenter", "siemens-digital", L1_MFG, "MES", "international", "自主", "high", "partial", "high", 0.88,
          ["MES与Teamcenter/MindSphere衔接", "制药与电子行业深"], ["MES links to TC/MindSphere", "Deep pharma and electronics"],
          ["实施成本高", "国产化竞品在钢铁/离散追赶"], ["High implementation cost", "Domestic rivals catching up"],
          ["制药", "电子", "汽车"], "https://plm.sw.siemens.com/"),
        p("blacklake-mes", "黑湖智造", "BlackLake Manufacturing", "blacklake", L1_MFG, "MES", "domestic", "自主", "mid", "pilot", "mid", 0.78,
          ["云端轻量MES", "中小工厂快速上线"], ["Cloud-lite MES", "Fast SME onboarding"],
          ["复杂工艺路线能力有限", "与ERP深度集成待加强"], ["Limited complex routing", "ERP depth needs work"],
          ["电子", "注塑", "五金"], "https://www.blacklake.cn/"),
    ]


def erp_products() -> list[dict]:
    return [
        p("yonyou-bip", "用友BIP", "Yonyou BIP", "yonyou", L1_BIZ, "ERP", "domestic", "自主", "high", "partial", "high", 0.90,
          ["大型企业数智化套件", "国产化信创适配完整"], ["Large enterprise digital suite", "Complete IT innovation adaptation"],
          ["高端制造业核心仍部分SAP", "云转型利润率承压"], ["Some manufacturing core still SAP", "Cloud transition margin pressure"],
          ["制造", "零售", "金融"], "https://www.yonyou.com/", ["sap-s4hana"], "600588.SH"),
        p("kingdee-cosmic", "金蝶云·苍穹", "Kingdee Cosmic", "kingdee", L1_BIZ, "ERP", "domestic", "自主", "high", "partial", "mid", 0.88,
          ["中小企业云ERP龙头", "低代码PaaS平台"], ["SME cloud ERP leader", "Low-code PaaS"],
          ["大型集团复杂制造弱于用友/SAP", "行业云深度参差"], ["Weaker complex manufacturing vs Yonyou/SAP", "Variable industry cloud depth"],
          ["零售", "制造", "服务业"], "https://www.kingdee.com/", ["sap-business-one"], "0268.HK"),
        p("digiwin-workflow", "鼎捷T100", "Digiwin T100", "digiwin", L1_BIZ, "ERP", "domestic", "自主", "high", "partial", "mid", 0.86,
          ["台湾背景深耕制造业ERP", "电子与机械优势"], ["Taiwan heritage manufacturing ERP", "Electronics and machinery strength"],
          ["大陆高端市场声量小于用友", "云产品占比提升中"], ["Lower mainland high-end mindshare", "Growing cloud mix"],
          ["电子", "机械", "汽车零部件"], "https://www.digiwin.com/", ["oracle-netsuite"], "300378.SZ"),
        p("inspur-gs", "浪潮GS Cloud", "Inspur GS Cloud", "inspur", L1_BIZ, "ERP", "domestic", "自主", "high", "partial", "mid", 0.84,
          ["国资与集团管控ERP", "信创软硬件一体"], ["SOE and group governance ERP", "IT innovation hardware-software bundle"],
          ["民营市场渗透有限", "用户体验待现代化"], ["Limited private sector penetration", "UX modernization needed"],
          ["国资", "集团管控", "政府"], "https://www.inspur.com/"),
        p("dcits-erp", "神州数码ERP", "DCITS ERP", "dcits", L1_BIZ, "ERP", "domestic", "自主", "mid", "pilot", "mid", 0.75,
          ["分销与供应链ERP", "IT服务渠道优势"], ["Distribution and supply chain ERP", "IT services channel"],
          ["自研ERP品牌声量弱", "以集成项目为主"], ["Weak own ERP brand", "Integration-project heavy"],
          ["分销", "IT", "零售"], "https://www.digitalchina.com/"),
        p("sap-s4hana", "SAP S/4HANA", "SAP S/4HANA", "sap", L1_BIZ, "ERP", "international", "自主", "mission_critical", "core", "high", 0.93,
          ["大型制造与跨国集团标准", "中国区客户基础深厚"], ["Standard for large manufacturing and multinationals", "Deep China installed base"],
          ["许可与实施成本极高", "地缘政治与替代压力"], ["Very high license and implementation", "Geopolitical displacement pressure"],
          ["汽车", "化工", "消费品"], "https://www.sap.com/products/erp.html", None, "SAP"),
        p("oracle-netsuite", "Oracle NetSuite", "Oracle NetSuite", "oracle", L1_BIZ, "ERP", "international", "自主", "high", "partial", "high", 0.88,
          ["云原生中小企业ERP", "跨境电商功能强"], ["Cloud-native SME ERP", "Strong cross-border e-commerce"],
          ["制造深度弱于SAP", "国内本地化支持有限"], ["Weaker manufacturing vs SAP", "Limited China localization"],
          ["跨境电商", "服务业", "批发"], "https://www.netsuite.com/"),
        p("microsoft-d365", "Dynamics 365", "Microsoft Dynamics 365", "microsoft", L1_BIZ, "ERP", "international", "自主", "high", "partial", "high", 0.87,
          ["与Office/Azure生态集成", "CRM+ERP一体"], ["Office/Azure ecosystem", "Unified CRM+ERP"],
          ["复杂制造MRP弱于SAP", "本地合作伙伴能力参差"], ["Weaker complex MRP vs SAP", "Variable partner capability"],
          ["零售", "服务", "制造"], "https://dynamics.microsoft.com/"),
        p("infor-cloudsuite", "Infor CloudSuite", "Infor CloudSuite", "infor", L1_BIZ, "ERP", "international", "自主", "high", "partial", "high", 0.85,
          ["行业云ERP（汽车/医疗/食品）", "微垂直功能深"], ["Industry cloud ERP", "Deep micro-vertical features"],
          ["品牌在中国弱于SAP/用友", "收购整合历史复杂"], ["Weaker China brand than SAP/Yonyou", "Complex acquisition history"],
          ["汽车", "医疗", "食品"], "https://www.infor.com/"),
        p("huawei-metaerp", "华为MetaERP", "Huawei MetaERP", "huawei", L1_BIZ, "ERP", "domestic", "自主", "mid", "pilot", "quote", 0.82,
          ["华为内部替代Oracle实践外溢", "信创全栈故事"], ["Huawei internal Oracle replacement export", "Full-stack IT innovation narrative"],
          ["对外商业化早期", "生态伙伴仍在招募"], ["Early external commercialization", "Partner ecosystem recruiting"],
          ["高科技", "制造", "大型集团"], "https://www.huawei.com/"),
        p("boke-erp", "博科ERP", "Boke ERP", "boke", L1_BIZ, "ERP", "domestic", "自主", "mid", "pilot", "mid", 0.72,
          ["元数据驱动可配置ERP", "长三角民营客户"], ["Metadata-driven configurable ERP", "Yangtze Delta private clients"],
          ["全国品牌弱", "云化程度有限"], ["Weak national brand", "Limited cloud"],
          ["贸易", "制造", "医药"], "https://www.bokesoft.com/"),
        p("ygsoft-erp", "远光ERP", "YGSOFT ERP", "ygsoft", L1_BIZ, "ERP", "domestic", "自主", "high", "core", "mid", 0.83,
          ["电力行业财务与集团管控", "国网南网深度渗透"], ["Power industry finance and group control", "Deep State Grid/CSG penetration"],
          ["行业垂直难跨域", "通用制造ERP弱"], ["Hard to cross verticals", "Weak general manufacturing ERP"],
          ["电力", "能源", "国资"], "https://www.ygsoft.com/", None, "002063.SZ"),
    ]


def bim_gis_products() -> list[dict]:
    return [
        p("glodon-bim", "广联达BIM", "Glodon BIM", "glodon", L1_RD, "BIM", "domestic", "自主", "high", "partial", "mid", 0.90,
          ["造价与施工BIM龙头", "数字造价云平台"], ["Leading cost and construction BIM", "Digital cost cloud"],
          ["设计端弱于Revit", "国际化仍在早期"], ["Weaker design vs Revit", "Early internationalization"],
          ["建筑", "基建", "房地产"], "https://www.glodon.com/", ["revit"], "002410.SZ"),
        p("supermap-gis", "超图GIS", "SuperMap GIS", "supermap", L1_PLAT, "GIS", "domestic", "自主", "high", "partial", "mid", 0.88,
          ["国产GIS基础平台龙头", "二三维一体化"], ["Leading domestic GIS platform", "2D/3D integration"],
          ["全球生态弱于Esri", "高端空间分析案例参差"], ["Weaker global ecosystem than Esri", "Variable advanced spatial analytics"],
          ["国土", "智慧城市", "交通"], "https://www.supermap.com/", ["arcgis"], "300036.SZ"),
        p("luban-bim", "鲁班工程管理", "Luban BIM", "luban", L1_RD, "BIM", "domestic", "自主", "mid", "partial", "mid", 0.80,
          ["施工阶段BIM深化", "钢筋算量优势"], ["Construction-phase BIM", "Rebar quantity strength"],
          ["设计协同弱", "市占受广联达挤压"], ["Weak design collaboration", "Share squeezed by Glodon"],
          ["施工", "基建"], "http://www.lubansoft.com/"),
        p("pinming-bim", "品茗BIM", "Pinming BIM", "pinming", L1_RD, "BIM", "domestic", "自主", "mid", "partial", "mid", 0.78,
          ["施工安全与物联网", "华东建筑市场强"], ["Construction safety and IoT", "Strong East China construction"],
          ["全国化仍在推进", "与国际标准对接中"], ["National expansion ongoing", "International standards alignment"],
          ["施工", "建筑"], "https://www.pinming.cn/", None, "688109.SH"),
        p("revit", "Autodesk Revit", "Autodesk Revit", "autodesk", L1_RD, "BIM", "international", "自主", "mission_critical", "core", "high", 0.93,
          ["建筑信息建模事实标准", "与中国设计院广泛使用"], ["BIM de-facto standard", "Widely used by China design institutes"],
          ["订阅成本高", "大模型协作弱于新兴云BIM"], ["High subscription", "Weaker large-model collab vs new cloud BIM"],
          ["建筑", "结构", "MEP"], "https://www.autodesk.com/products/revit"),
        p("microstation", "Bentley MicroStation", "Bentley MicroStation", "bentley", L1_RD, "BIM", "international", "自主", "high", "partial", "high", 0.88,
          ["基础设施BIM强项", "线性工程与数字孪生"], ["Infrastructure BIM strength", "Linear engineering and digital twin"],
          ["房建市场弱于Revit", "学习资源相对少"], ["Weaker building vs Revit", "Fewer learning resources"],
          ["交通", "市政", "能源基建"], "https://www.bentley.com/"),
        p("archicad", "Graphisoft ArchiCAD", "Graphisoft ArchiCAD", "graphisoft", L1_RD, "BIM", "international", "自主", "high", "partial", "high", 0.86,
          ["建筑师友好BIM", "OPEN BIM互操作"], ["Architect-friendly BIM", "OPEN BIM interoperability"],
          ["国内市占低于Revit", "施工阶段工具链弱"], ["Lower China share than Revit", "Weaker construction toolchain"],
          ["建筑", "室内设计"], "https://graphisoft.com/solutions/archicad"),
        p("arcgis", "Esri ArcGIS", "Esri ArcGIS", "esri", L1_PLAT, "GIS", "international", "自主", "mission_critical", "core", "high", 0.91,
          ["全球GIS平台标杆", "空间分析与生态完善"], ["Global GIS platform benchmark", "Rich spatial analytics ecosystem"],
          ["国产化替代政策压力", "高级模块授权昂贵"], ["Localization policy pressure", "Expensive advanced modules"],
          ["政府", "公用事业", "交通"], "https://www.esri.com/"),
        p("feidu-dt", "飞渡科技数字孪生", "Feidu Digital Twin", "feidu", L1_PLAT, "GIS", "domestic", "自主", "mid", "pilot", "mid", 0.76,
          ["城市与园区数字孪生（虚实映射能力）", "国产三维 GIS 引擎"], ["City/campus digital twin (physical-virtual mapping)", "Domestic 3D GIS engine"],
          ["产品标准化程度低", "依赖项目交付"], ["Low product standardization", "Project delivery heavy"],
          ["智慧城市", "园区"], "https://www.feidutech.com/"),
        p("southsurvey-gis", "南方数码GIS", "South Survey GIS", "south", L1_PLAT, "GIS", "domestic", "自主", "mid", "partial", "mid", 0.78,
          ["测绘地理信息", "国土调查传统优势"], ["Surveying and geoinformatics", "Land survey heritage"],
          ["平台化弱于超图", "软件营收占比提升中"], ["Less platform than SuperMap", "Growing software revenue mix"],
          ["测绘", "国土", "水利"], "https://www.southgis.com/"),
        p("sunway-bim", "山维BIM", "Sunway BIM", "sunway", L1_RD, "BIM", "domestic", "自主", "mid", "pilot", "mid", 0.72,
          ["城市规划BIM", "三维城市建模"], ["Urban planning BIM", "3D city modeling"],
          ["全国知名度有限", "施工链条未覆盖"], ["Limited national fame", "No construction chain coverage"],
          ["规划", "市政"], "http://www.sunwaysoft.com/"),
        p("cscec-digital", "中建数字建造", "CSCEC Digital Construction", "cscec", L1_RD, "BIM", "domestic", "自主", "high", "partial", "quote", 0.80,
          ["最大承包商数字化实践", "项目级BIM标准输出"], ["Largest contractor digital practice", "Project BIM standards export"],
          ["产品对外商业化有限", "依赖中建体系"], ["Limited external productization", "CSCEC ecosystem dependent"],
          ["建筑", "基建"], "https://www.cscec.com/"),
        p("zwsoft-bim", "中望BIM", "ZWSOFT BIM", "zwcad", L1_RD, "BIM", "domestic", "自主", "mid", "pilot", "mid", 0.75,
          ["国产BIM设计尝试", "与中望CAD协同"], ["Domestic BIM design attempt", "Synergy with ZWCAD"],
          ["功能深度远小于Revit", "市场导入早期"], ["Far shallower than Revit", "Early market entry"],
          ["建筑", "结构"], "https://www.zwsoft.cn/"),
        p("mapbox-cn", "Mapbox GL", "Mapbox GL", "mapbox", L1_PLAT, "GIS", "international", "自主", "high", "partial", "mid", 0.84,
          ["Web地图可视化", "开发者生态活跃"], ["Web map visualization", "Active developer ecosystem"],
          ["国内合规与底图限制", "政企项目常需国产底图"], ["China compliance and basemap limits", "Gov projects need domestic basemaps"],
          ["互联网", "物流", "LBS"], "https://www.mapbox.com/"),
    ]


def platform_products() -> list[dict]:
    return [
        p("huawei-fusionplant", "华为FusionPlant", "Huawei FusionPlant", "huawei", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "quote", 0.85,
          ["制造业数字化转型平台", "5G+工业互联网案例"], ["Manufacturing digital platform", "5G+IIoT cases"],
          ["生态依赖华为云与伙伴", "中立性受质疑"], ["Huawei Cloud and partner dependent", "Neutrality questions"],
          ["制造", "电子", "矿山"], "https://www.huaweicloud.com/product/fusionplant.html"),
        p("alibaba-industrial-brain", "阿里云工业大脑", "Alibaba Industrial Brain", "alibaba", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "quote", 0.84,
          ["数据智能与预测性维护", "纺织印染等行业案例"], ["Data intelligence and predictive maintenance", "Textile industry cases"],
          ["OT连接能力依赖伙伴", "重云轻边缘"], ["OT connectivity via partners", "Cloud-heavy edge-light"],
          ["纺织", "钢铁", "水泥"], "https://www.aliyun.com/solution/manufacturing/industrial_brain"),
        p("tencent-wemake", "腾讯云WeMake", "Tencent WeMake", "tencent", L1_PLAT, "工业互联网", "domestic", "自主", "mid", "pilot", "quote", 0.78,
          ["消费电子与3C数字化", "小程序生态触达"], ["Consumer electronics digitalization", "Mini-program ecosystem reach"],
          ["流程工业案例少", "平台市占低于阿里华为"], ["Few process industry cases", "Lower share than Alibaba/Huawei"],
          ["3C", "消费电子"], "https://cloud.tencent.com/solution/WeMake"),
        p("baidu-industrial", "百度智能云工业", "Baidu AI Cloud Industrial", "baidu", L1_PLAT, "工业互联网", "domestic", "自主", "mid", "pilot", "quote", 0.76,
          ["AI质检与视觉检测", "大模型+工业场景"], ["AI inspection and vision", "LLM plus industrial scenarios"],
          ["平台完整性弱于头部", "OT落地依赖集成商"], ["Less complete platform than leaders", "OT via integrators"],
          ["汽车", "电子", "能源"], "https://cloud.baidu.com/solution/industry/manufacturing.html"),
        p("rootcloud", "树根互联根云", "Rootcloud RootCloud", "rootcloud", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "mid", 0.82,
          ["工程机械IoT龙头", "跨行业设备互联"], ["Construction machinery IoT leader", "Cross-industry equipment connectivity"],
          ["非装备行业渗透慢", "与三一生态绑定印象"], ["Slow non-equipment penetration", "Sany ecosystem perception"],
          ["工程机械", "装备制造"], "https://www.rootcloud.com/"),
        p("casicloud-indics", "航天云网INDICS", "CASIC INDICS", "casicloud", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "quote", 0.80,
          ["国家级工业互联网平台", "航天供应链背景"], ["National IIoT platform", "Aerospace supply chain heritage"],
          ["市场化运营能力参差", "用户体验待提升"], ["Variable commercial operations", "UX needs improvement"],
          ["航天", "制造", "国资"], "https://www.casicloud.com/"),
        p("yonyou-iip", "用友精智", "Yonyou Industrial Internet", "yonyou", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "mid", 0.83,
          ["ERP+IoT一体化", "大型企业集团客户"], ["ERP plus IoT integration", "Large enterprise group clients"],
          ["设备连接协议覆盖参差", "与专业IIoT平台竞争"], ["Variable device protocol coverage", "Competes with specialist IIoT"],
          ["制造", "能源", "钢铁"], "https://www.yonyou.com/"),
        p("thingworx", "PTC ThingWorx", "PTC ThingWorx", "ptc", L1_PLAT, "工业互联网", "international", "自主", "high", "partial", "high", 0.87,
          ["工业物联网应用平台", "与Windchill/Creo协同"], ["Industrial IoT application platform", "Windchill/Creo synergy"],
          ["国内部署与合规成本", "本土竞品性价比压力"], ["China deployment and compliance cost", "Local value rivals"],
          ["制造", "服务", "零售"], "https://www.ptc.com/en/products/thingworx"),
        p("mindsphere", "Siemens MindSphere", "Siemens MindSphere", "siemens-digital", L1_PLAT, "工业互联网", "international", "自主", "high", "partial", "high", 0.86,
          ["工业云与数字孪生", "与Opcenter/Teamcenter集成"], ["Industrial cloud and digital twin", "Opcenter/Teamcenter integration"],
          ["在华推广弱于本土平台", "定价与生态开放度争议"], ["Weaker China push than local platforms", "Pricing and openness debates"],
          ["制造", "能源", "交通"], "https://plm.sw.siemens.com/"),
        p("ge-predix", "GE Predix", "GE Predix", "ge", L1_PLAT, "工业互联网", "international", "自主", "mid", "pilot", "high", 0.80,
          ["能源与航空资产性能管理", "历史光环大"], ["Energy and aviation APM heritage", "Large historical brand"],
          ["战略收缩后在华声量下降", "生态活跃度低于AWS/Azure"], ["Reduced China presence after strategy shift", "Less ecosystem than hyperscalers"],
          ["能源", "航空", "医疗"], "https://www.ge.com/digital/predix"),
        p("sap-btp", "SAP Business Technology Platform", "SAP BTP", "sap", L1_PLAT, "工业互联网", "international", "自主", "high", "partial", "high", 0.85,
          ["ERP扩展与集成平台", "大型企业数据治理"], ["ERP extension and integration", "Large enterprise data governance"],
          ["工业物联非核心强项", "实施复杂度高"], ["Industrial IoT not core strength", "High implementation complexity"],
          ["制造", "零售", "化工"], "https://www.sap.com/products/technology-platform.html"),
        p("meicloud", "美云智数", "Meicloud", "midea", L1_PLAT, "工业互联网", "domestic", "自主", "mid", "partial", "mid", 0.79,
          ["美的工业互联网外溢", "供应链数字化"], ["Midea IIoT export", "Supply chain digitalization"],
          ["对外品牌弱于卡奥斯", "行业复制仍在验证"], ["Weaker external brand than COSMOPlat", "Cross-industry replication proving"],
          ["家电", "供应链", "制造"], "https://www.meicloud.com/"),
        p("unigroup-cloud", "紫光云工业", "Unigroup Industrial Cloud", "unigroup", L1_PLAT, "工业互联网", "domestic", "自主", "mid", "pilot", "quote", 0.72,
          ["芯片与ICT背景工业云", "信创算力故事"], ["Chip and ICT heritage industrial cloud", "IT innovation compute narrative"],
          ["经营波动影响市场信心", "工业场景案例有限"], ["Business volatility hurts confidence", "Limited industrial cases"],
          ["电子", "政府", "制造"], "https://www.unicloud.com/"),
        p("haier-cosmoplat-platform", "卡奥斯COSMOPlat", "COSMOPlat", "haier", L1_PLAT, "工业互联网", "domestic", "自主", "high", "partial", "mid", 0.84,
          ["跨行业工业互联网平台", "大规模定制模式输出"], ["Cross-industry IIoT platform", "Mass customization export"],
          ["盈利能力与估值波动", "制造业外复制难度"], ["Profitability and valuation swings", "Hard replication outside manufacturing"],
          ["家电", "服装", "机械"], "https://www.cosmoplat.com/"),
    ]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    agents = {
        "a1-eda": eda_products(),
        "a2-cad": cad_products(),
        "a3-cae-cam": cae_products(),
        "a4-plm-mbse": plm_products(),
        "a5-dcs-scada": mes_dcs_products(),
        "a7-erp": erp_products(),
        "a8-bim-gis": bim_gis_products(),
        "a8-platform": platform_products(),
    }
    total = 0
    for name, products in agents.items():
        path = OUT / f"{name}.json"
        path.write_text(json.dumps({"agent": name, "products": products}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{name}: {len(products)} products")
        total += len(products)
    print(f"Total: {total} products → {OUT}")


if __name__ == "__main__":
    main()
