#!/usr/bin/env python3
"""One-shot merge of pre-2022 and 2025-2026 timeline research into policies/breakthroughs."""
from __future__ import annotations

import json
from pathlib import Path

from migrate_breakthrough_contract import normalize_milestone_source_contract

ROOT = Path(__file__).resolve().parent.parent
POLICIES_PATH = ROOT / "assets" / "data" / "policies.json"
BREAKTHROUGHS_PATH = ROOT / "assets" / "data" / "breakthroughs.json"

STRIP_POLICY_KEYS = {"category_l1", "category_l2", "policy_type", "confidence"}

PRE2022_POLICIES = [
    {
        "id": "863-plan-launch-1986",
        "date": "1986-03",
        "target_deadline": "1996-12",
        "title_zh": "863计划启动：100亿元国家高技术研究发展专项",
        "title_en": "863 Plan launched with ¥10B national high-tech R&D funding",
        "metric_zh": "863计划专项拨款",
        "metric_en": "863 Plan dedicated funding",
        "target_value": 100,
        "target_unit_zh": "亿元",
        "target_unit_en": "CNY bn",
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "1986年10月中央政治局扩大会议批准100亿元实施863计划（载人航天等主题）",
        "actual_note_en": "Oct 1986 Politburo expanded meeting approved ¥10B for 863 themes incl. space/automation",
        "summary_zh": "国家高技术研究发展计划启动，为CIMS/CAD/自动化等工业软件科研提供顶层资金渠道",
        "summary_en": "National High-Tech R&D Program launch—top-level funding channel for CIMS/CAD/automation R&D",
        "source_url": "https://www.cmse.gov.cn/ztbd/xwzt/qzxzgcllszntbzt/fzlc/200909/t20090925_39615.html",
    },
    {
        "id": "cad-application-program-1992",
        "date": "1992-04",
        "target_deadline": "2000-12",
        "title_zh": "国务院批复 CAD 应用工程（国办函〔1992〕13号）",
        "title_en": "State Council approves National CAD Application Program",
        "metric_zh": "CAD应用示范/推广企业数",
        "metric_en": "CAD demo / rollout enterprises",
        "target_value": 600,
        "target_unit_zh": "家示范企业",
        "target_unit_en": "demo plants",
        "actual_value": 100000,
        "actual_as_of": "2000",
        "actual_note_zh": "九五验收：600余家示范、3000余家推广、近10万家普及CAD（科技部口径）",
        "actual_note_en": "9th FYP review: 600+ demos, 3,000+ rollout, ~100k plants adopted CAD (MOST boundary)",
        "summary_zh": "首个国务院层面CAD应用工程，推动国产二维CAD与外资工具规模化落地",
        "summary_en": "First State Council-level CAD rollout—scaled domestic 2D CAD alongside foreign tools",
        "source_url": "https://www.most.gov.cn/xxgk/xinxifenlei/fdzdgknr/qtwj/qtwj2010before/200312/t20031209_143209.html",
    },
    {
        "id": "guofa-18-software-ic-2000",
        "date": "2000-06",
        "target_deadline": None,
        "title_zh": "鼓励软件产业和集成电路产业发展若干政策（国发〔2000〕18号）",
        "title_en": "Policies to Encourage Software and IC Industries (Guofa [2000] No. 18)",
        "metric_zh": "软件/集成电路企业所得税优惠",
        "metric_en": "Software/IC corporate income tax incentives",
        "target_value": None,
        "target_unit_zh": "两免三减半",
        "target_unit_en": "2-yr exempt + 3-yr half rate",
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "EDA/IP设计视同软件产业；2015年国务院宣布18号文失效，由2011年4号文接续",
        "actual_note_en": "EDA/IP design treated as software; Doc 18 repealed 2015, superseded by Doc 4 (2011)",
        "summary_zh": "早期软件与集成电路（含EDA）产业化的国家级财税政策基石",
        "summary_en": "Foundational national fiscal policy for software, IC design, and EDA industrialization",
        "source_url": "https://www.gov.cn/gongbao/content/2000/content_60310.htm",
    },
    {
        "id": "manufacturing-informatization-2002",
        "date": "2002-01",
        "target_deadline": "2005-12",
        "title_zh": "「十五」制造业信息化工程启动（科技部8亿元引导）",
        "title_en": "10th FYP Manufacturing Informatization Program (¥800M MOST guidance)",
        "metric_zh": "制造业信息化参与企业",
        "metric_en": "Manufacturing informatization participating enterprises",
        "target_value": 4000,
        "target_unit_zh": "家",
        "target_unit_en": "enterprises",
        "actual_value": 4000,
        "actual_as_of": "2005",
        "actual_note_zh": "中央8亿+地方13亿+企业90亿；覆盖数字化设计/管理/制造（科技部口径）",
        "actual_note_en": "¥0.8B central + ¥1.3B local + ¥9B enterprise; digital design/mfg/management scope",
        "summary_zh": "CAD/CIMS之后最大规模的制造业数字化专项，推动PLM/MES/ERP应用",
        "summary_en": "Largest post-CAD/CIMS manufacturing digitization program driving PLM/MES/ERP adoption",
        "source_url": "http://www.kepu365.com/kepu/KXBL/200701/114984.html",
    },
    {
        "id": "hegaoji-launch-2008",
        "date": "2008-04",
        "target_deadline": "2020-12",
        "title_zh": "核高基重大专项启动（含EDA工具攻关）",
        "title_en": "核高基 mega-project launched (includes EDA tools)",
        "metric_zh": "核高基十一五课题/经费",
        "metric_en": "核高基 11th FYP projects / funding",
        "target_value": 220,
        "target_unit_zh": "个课题",
        "target_unit_en": "projects",
        "actual_value": 196,
        "actual_as_of": "2010",
        "actual_note_zh": "220课题、总经费196.4亿元（中央84+自筹111，十一五口径）",
        "actual_note_en": "220 projects, ¥19.64B total (¥8.4B central + ¥11.1B co-funding, 11th FYP boundary)",
        "summary_zh": "国家科技重大专项直接资助CPU/OS/EDA等基础软件与芯片工具链",
        "summary_en": "National mega-project funding CPU/OS/EDA and basic software toolchain",
        "source_url": "https://www.most.gov.cn/xwzx/twzb/fbh17112001/twbbwzsl/201711/t20171124_136445.html",
    },
    {
        "id": "guofa-4-software-ic-2011",
        "date": "2011-01",
        "target_deadline": None,
        "title_zh": "进一步鼓励软件产业和集成电路产业政策（国发〔2011〕4号）",
        "title_en": "Further Policies for Software and IC Industries (Guofa [2011] No. 4)",
        "metric_zh": None,
        "metric_en": None,
        "target_value": None,
        "target_unit_zh": None,
        "target_unit_en": None,
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "接续国发18号，强化软件与集成电路（含设计/EDA）扶持",
        "actual_note_en": "Successor to Doc 18; strengthens software and IC design (incl. EDA) support",
        "summary_zh": "2010年代软件与工业软件产业政策环境的国务院接续文件",
        "summary_en": "State Council continuation of 2010s software/industrial software policy environment",
        "source_url": "http://jsnews.jschina.com.cn/zt2024/fzsxxxpt/hdxf/fgxwj/202404/t20240424_3396470.shtml",
    },
    {
        "id": "integration-informatization-industrialization-2011",
        "date": "2011-07",
        "target_deadline": "2015-12",
        "title_zh": "加快推进信息化与工业化深度融合若干意见",
        "title_en": "Opinions on in-depth integration of informatization and industrialization",
        "metric_zh": "两化融合节能减排示范项目",
        "metric_en": "Integration & energy-saving demo projects",
        "target_value": 80,
        "target_unit_zh": "个",
        "target_unit_en": "projects",
        "actual_value": 80,
        "actual_as_of": "2011",
        "actual_note_zh": "首批80个项目（工信厅信〔2011〕164号）",
        "actual_note_en": "First batch of 80 projects (MIIT Letter [2011] No. 164)",
        "summary_zh": "「两化融合」纲领性文件，推动MES/ERP/DCS等工业软件渗透制造环节",
        "summary_en": "Cornerstone 'integration of informatization & industrialization' policy for MES/ERP/DCS penetration",
        "source_url": "https://www.gov.cn/gongbao/content/2011/content_1967421.htm",
    },
    {
        "id": "ic-industry-guideline-2014",
        "date": "2014-06",
        "target_deadline": "2030-12",
        "title_zh": "国家集成电路产业发展推进纲要（设立大基金）",
        "title_en": "National IC Industry Development Guidelines (Big Fund)",
        "metric_zh": "国家集成电路产业投资基金",
        "metric_en": "National IC Industry Investment Fund",
        "target_value": None,
        "target_unit_zh": "市场化基金",
        "target_unit_en": "market-oriented fund",
        "actual_value": None,
        "actual_as_of": "2014",
        "actual_note_zh": "2014年6月印发；大基金一期2014年9月成立，规模约1387亿元（后续披露）",
        "actual_note_en": "Issued Jun 2014; Big Fund Phase I est. Sep 2014, ~¥138.7B (later disclosures)",
        "summary_zh": "集成电路（含EDA/IP）国家战略，为大基金投资华大九天等提供依据",
        "summary_en": "National IC strategy (incl. EDA/IP)—policy basis for Big Fund EDA investments",
        "source_url": "https://www.cac.gov.cn/2014-06/26/c_1111325916.htm",
    },
    {
        "id": "made-in-china-2025",
        "date": "2015-05",
        "target_deadline": "2025-12",
        "title_zh": "中国制造2025（国发〔2015〕28号）",
        "title_en": "Made in China 2025 (Guofa [2015] No. 28)",
        "metric_zh": "智能制造主攻方向",
        "metric_en": "Intelligent manufacturing as main thrust",
        "target_value": None,
        "target_unit_zh": "战略任务",
        "target_unit_en": "strategic tasks",
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "解读明确高端工业软件依赖进口、需补工业2.0→3.0差距",
        "actual_note_en": "Official interpretation flags imported high-end industrial software dependency",
        "summary_zh": "制造强国十年行动纲领，智能制造与工业软件自主可控的总纲",
        "summary_en": "Decade-long manufacturing power roadmap—intelligent manufacturing & software autonomy",
        "source_url": "https://www.ndrc.gov.cn/xxgk/zcfb/qt/201505/t20150520_967388.html",
    },
    {
        "id": "mohurd-bim-guidance-2015",
        "date": "2015-06",
        "target_deadline": "2020-12",
        "title_zh": "推进建筑信息模型（BIM）应用指导意见",
        "title_en": "Guidance on promoting BIM application",
        "metric_zh": "政府投资及大型项目BIM应用",
        "metric_en": "BIM adoption on public & large projects",
        "target_value": None,
        "target_unit_zh": "全面应用",
        "target_unit_en": "full adoption",
        "actual_value": None,
        "actual_as_of": "2020",
        "actual_note_zh": "建质函〔2015〕159号；要求2020年前大型项目全面应用BIM",
        "actual_note_en": "Jianzhi Letter [2015] No. 159; targets full BIM on large projects by 2020",
        "summary_zh": "国家级BIM应用政策，推动国产BIM/GIS软件与协同平台",
        "summary_en": "National BIM policy driving domestic BIM/GIS software and collaboration platforms",
        "source_url": "http://zjj.sz.gov.cn/xxgk/zcfgs/zcfg/content/post_9728322.html",
    },
    {
        "id": "intelligent-manufacturing-plan-2016",
        "date": "2016-09",
        "target_deadline": "2020-12",
        "title_zh": "智能制造发展规划（2016-2020年）",
        "title_en": "Intelligent Manufacturing Development Plan (2016–2020)",
        "metric_zh": "工业软件市场满足率",
        "metric_en": "Industrial software market satisfaction rate",
        "target_value": 50,
        "target_unit_zh": "%",
        "target_unit_en": "%",
        "actual_value": None,
        "actual_as_of": "2020",
        "actual_note_zh": "与2021十四五智能制造规划衔接；2025年满足率目标70%（后续文件）",
        "actual_note_en": "Links to 2021 14th FYP smart manufacturing plan; 70% target by 2025 in later doc",
        "summary_zh": "十三五智能制造纲领，明确工业软件为智能工厂核心支撑",
        "summary_en": "13th FYP intelligent manufacturing plan—industrial software as smart-factory backbone",
        "source_url": "http://www.mof.gov.cn/gp/xxgkml/jjjss/201612/t20161208_2512227.htm",
    },
    {
        "id": "xinchuang-committee-2016",
        "date": "2016-01",
        "target_deadline": "2027-12",
        "title_zh": "信息技术应用创新工作委员会成立（信创）",
        "title_en": "IT Application Innovation Working Committee established",
        "metric_zh": None,
        "metric_en": None,
        "target_value": None,
        "target_unit_zh": None,
        "target_unit_en": None,
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "界定IT基础设施/基础软件/应用软件/信息安全；启动2+8+N国产替代路线",
        "actual_note_en": "Scopes infra/base/app/security software; starts 2+8+N domestic substitution path",
        "summary_zh": "信创政策体系命名与组织起点，后续延伸至CAD/PLM/ERP国产化采购",
        "summary_en": "Naming and institutional start of 信创—later extended to CAD/PLM/ERP procurement",
        "source_url": "https://36kr.com/p/2329929920881545",
    },
    {
        "id": "industrial-internet-guidance-2017",
        "date": "2017-11",
        "target_deadline": "2025-12",
        "title_zh": "深化「互联网+先进制造业」发展工业互联网指导意见",
        "title_en": "Guidance on developing the Industrial Internet",
        "metric_zh": "工业互联网网络基础设施",
        "metric_en": "Industrial Internet network infrastructure",
        "target_value": None,
        "target_unit_zh": "2025基本建成",
        "target_unit_en": "basically built by 2025",
        "actual_value": None,
        "actual_as_of": None,
        "actual_note_zh": "国务院2017-11-27发布；构建网络、平台、安全三大体系",
        "actual_note_en": "State Council release 2017-11-27; network/platform/security systems",
        "summary_zh": "工业互联网国家级政策，推动工业APP与MES/SCADA平台化",
        "summary_en": "National Industrial Internet policy—platformization of industrial apps, MES, SCADA",
        "source_url": "https://www.gov.cn/zhengce/zhengceku/2017-11/27/content_5242582.htm",
    },
]

POLICY_2025_2026 = [
    {
        "id": "miit-ai-manufacturing-2027-kpi",
        "date": "2026-01",
        "target_deadline": "2027-12",
        "title_zh": "「人工智能+制造」专项行动：2027量化目标",
        "title_en": "AI + Manufacturing action: 2027 quantitative targets",
        "metric_zh": "工业高质量数据集 / 典型应用场景 / 标杆企业",
        "metric_en": "Industrial datasets / exemplar scenarios / benchmark enterprises",
        "target_value": None,
        "target_unit_zh": "100数据集;500场景;1000企业",
        "target_unit_en": "100 datasets; 500 scenarios; 1000 enterprises",
        "actual_value": None,
        "actual_as_of": "2026",
        "actual_note_zh": "工信部联科〔2025〕279号；软件和信息技术服务行业另提软件全生命周期智能工具链",
        "actual_note_en": "MIIT Doc 279; software sector guide adds full-lifecycle intelligent tool chain",
        "summary_zh": "八部门「人工智能+制造」专项行动及配套行业转型指引",
        "summary_en": "Eight-ministry AI+Manufacturing special action with sector transformation guide",
        "source_url": "https://www.miit.gov.cn/jgsj/kjs/wjfb/art/2026/art_5ea5b1663f264fcea69df0ab00d1f6f3.html",
    },
    {
        "id": "gov-procurement-domestic-20pct",
        "date": "2025-09",
        "target_deadline": "2031-12",
        "title_zh": "政府采购本国产品 20% 价格评审优惠",
        "title_en": "Government procurement: 20% price preference for domestic products",
        "metric_zh": "本国产品报价评审扣除比例",
        "metric_en": "Domestic product price evaluation deduction",
        "target_value": 20,
        "target_unit_zh": "%",
        "target_unit_en": "%",
        "actual_value": 20,
        "actual_as_of": "2026",
        "actual_note_zh": "国办发〔2025〕34号，2026-01-01施行；组件成本占比分产品过渡期3–5年",
        "actual_note_en": "Guoban [2025] No.34 effective 2026-01-01; component-cost ratios phased 3–5 years",
        "summary_zh": "构建政府采购本国产品标准与价格支持政策",
        "summary_en": "Domestic product standards and price support in government procurement",
        "source_url": "https://www.gov.cn/gongbao/2025/issue_12346/202510/content_7044731.html",
    },
    {
        "id": "cesi-industrial-software-2940-2024",
        "date": "2025-06",
        "target_deadline": "2028-12",
        "title_zh": "电子五所：2024年工业软件市场规模约2940亿元",
        "title_en": "CESI: 2024 industrial software market ~¥294B",
        "metric_zh": "工业软件市场规模",
        "metric_en": "Industrial software market size",
        "target_value": 4000,
        "target_unit_zh": "亿元",
        "target_unit_en": "CNY bn",
        "actual_value": 2940,
        "actual_as_of": "2024",
        "actual_note_zh": "占全球7.6%；与既有第三方3197/3541口径并存，引用时需标注来源",
        "actual_note_en": "7.6% global share; coexists with other analyst boundaries (3197/3541)",
        "summary_zh": "《中国工业软件产业发展研究报告（2025）》南京软件大会发布",
        "summary_en": "China Industrial Software Report (2025) at Nanjing Software Congress",
        "source_url": "https://www.nanjing.gov.cn/hdjl/wszb/2025njrjdh/xgbd/202506/t20250618_5588391.html",
    },
    {
        "id": "t-cie-311-cad-security-2025",
        "date": "2025-03",
        "target_deadline": None,
        "title_zh": "T/CIE 311-2025 三维CAD软件安全性测评规范",
        "title_en": "T/CIE 311-2025 3D CAD security evaluation standard",
        "metric_zh": "团体标准项数（CAD测评系列）",
        "metric_en": "Group standards in 3D CAD evaluation series",
        "target_value": 7,
        "target_unit_zh": "项",
        "target_unit_en": "standards",
        "actual_value": 7,
        "actual_as_of": "2025",
        "actual_note_zh": "含安全性/功能/性能/兼容性/测试过程等，2025-03-31实施",
        "actual_note_en": "Security, function, performance, compatibility, test process, etc.; effective 2025-03-31",
        "summary_zh": "国产三维CAD信创测评与采购对标标准体系",
        "summary_en": "Evaluation framework for domestic 3D CAD procurement",
        "source_url": "https://www.ndls.org.cn/standard/detail/00b0d0aaf2e0b4625a67d2cd3d94749d",
    },
    {
        "id": "xinchuang-harmonyos-desktop-ii-2026",
        "date": "2026-01",
        "target_deadline": "2029-01",
        "title_zh": "安全可靠测评：HarmonyOS 桌面OS Ⅱ级",
        "title_en": "Secure & reliable eval: HarmonyOS desktop OS Level II",
        "metric_zh": "桌面操作系统安全可靠等级",
        "metric_en": "Desktop OS secure & reliable level",
        "target_value": 2,
        "target_unit_zh": "级(Ⅱ最高)",
        "target_unit_en": "level (II highest)",
        "actual_value": 2,
        "actual_as_of": "2026",
        "actual_note_zh": "2026年第1号公告；有效期三年；支撑鸿蒙电脑+国产CAD部署",
        "actual_note_en": "2026 notice #1; valid 3 years; enables Harmony PC + domestic CAD",
        "summary_zh": "信创操作系统与工业软件终端生态节点",
        "summary_en": "Xinchuang OS milestone for industrial software endpoints",
        "source_url": "https://www.itsec.gov.cn/aqkkcp/cpgg/202601/t20260116_249958.html",
    },
    {
        "id": "xinchuang-ai-chip-eval-2026",
        "date": "2026-05",
        "target_deadline": "2029-05",
        "title_zh": "安全可靠测评 2026-2：AI训练推理芯片首批目录",
        "title_en": "Secure & reliable eval 2026-2: first AI train/inference chip list",
        "metric_zh": "入围AI芯片产品数",
        "metric_en": "Listed AI accelerator products",
        "target_value": 9,
        "target_unit_zh": "款",
        "target_unit_en": "products",
        "actual_value": 9,
        "actual_as_of": "2026",
        "actual_note_zh": "含昇腾310/910、海光DCU等；同公告含4款数据库Ⅱ级",
        "actual_note_en": "Includes Ascend 310/910, Hygon DCU; same notice lists 4 DBs at Level II",
        "summary_zh": "工业AI算力信创白名单节点",
        "summary_en": "Xinchuang whitelist for industrial AI compute",
        "source_url": "https://www.itsec.gov.cn/aqkkcp/cpgg/202605/t20260526_259396.html",
    },
]

NEW_MILESTONES = [
    {
        "id": "yonyou-founded-1988",
        "date": "1988-12",
        "vendor_id": "yonyou",
        "category_l2": "ERP",
        "headline_zh": "用友在中关村创立，开启国产财务/ERP 软件产业化",
        "headline_en": "Yonyou founded in Zhongguancun — domestic finance/ERP software industrialization begins",
        "before_gap_zh": "1980年代中国企业财务与经营管理软件几乎空白，大型集团依赖手工账簿或外资方案",
        "before_gap_en": "1980s Chinese enterprises had almost no packaged finance/ERP software; large groups relied on manual ledgers or foreign suites",
        "achievement_zh": "王文京1988年创立用友，从财务软件起步，2001年上市，后推出 U8/NC 等 ERP 产品，打破高端 ERP 外资垄断叙事",
        "achievement_en": "Wang Wenjing founded Yonyou in 1988 with accounting software, listed in 2001, later shipped U8/NC ERP — breaking foreign dominance in enterprise management software",
        "still_missing_zh": "全球化多法人复杂核算、高端制造业深度 MES/PLM 集成仍弱于 SAP S/4HANA",
        "still_missing_en": "Global multi-entity accounting and deep MES/PLM integration still trail SAP S/4HANA",
        "evidence_level": "case_study",
        "sources": [
            {"url": "http://www.zqrb.cn/gscy/zjssgongsi/2018-12-26/A1545836900583.html", "title": "用友发展历程", "accessed": "2026-06"},
        ],
        "confidence": 0.88,
        "related_policy_ids": [],
    },
    {
        "id": "supcon-jx100-dcs-1993",
        "date": "1993-12",
        "vendor_id": "supcon",
        "product_ids": ["supcon-supos"],
        "category_l2": "DCS",
        "headline_zh": "中控 JX-100 DCS 在巨化投运，打破外资流程控制垄断",
        "headline_en": "SUPCON JX-100 DCS commissioned at Juhua — breaks foreign process-control monopoly",
        "before_gap_zh": "1990年代前流程工业 DCS 由 Emerson/Yokogawa/Honeywell 主导，国产系统市占不足 30%，价格高昂",
        "before_gap_en": "Before the 1990s, process DCS was Emerson/Yokogawa/Honeywell dominated with <30% domestic share and high import prices",
        "achievement_zh": "褚健1993年创立浙大自动化公司，推出国内首套 1:1 热冗余 DCS；1993 年底 JX-100 在浙江巨化锦纶装置投运，价格约为进口三分之一",
        "achievement_en": "Chu Jian founded ZJU Automation in 1993 with China's first 1:1 hot-standby DCS; JX-100 commissioned at Juhua caprolactam unit late 1993 at ~one-third import price",
        "still_missing_zh": "高端现场仪表、大型乙烯全套集成经验仍部分依赖进口；海外标杆项目少于欧美厂商",
        "still_missing_en": "High-end field instruments and mega-ethylene integration partly imported; fewer overseas reference projects than US/EU vendors",
        "metrics": [
            {"label_zh": "相对进口价格", "label_en": "vs import price", "value": "~33%", "verified": True},
        ],
        "evidence_level": "case_study",
        "sources": [
            {"url": "https://paper.people.com.cn/zgjjzk/html/2020-12/15/content_2027478.htm", "title": "中控技术发展史", "accessed": "2026-06"},
        ],
        "confidence": 0.9,
        "related_policy_ids": [],
    },
    {
        "id": "kingdee-founded-1993",
        "date": "1993-08",
        "vendor_id": "kingdee",
        "category_l2": "ERP",
        "headline_zh": "金蝶在深圳创立，形成「北用友、南金蝶」国产 ERP 格局",
        "headline_en": "Kingdee founded in Shenzhen — 'Yonyou north, Kingdee south' domestic ERP duopoly",
        "before_gap_zh": "1990年代初国产经营管理软件缺乏规模化厂商，中小企业难以获得可负担的 ERP 套件",
        "before_gap_en": "Early 1990s lacked scaled domestic management-software vendors; SMEs could not afford ERP suites",
        "achievement_zh": "徐少春1993年创立金蝶；1999年推出 K3 ERP，2001年港交所上市，后转型云 ERP/精斗云，与用友构成国产经营管理软件双寡头",
        "achievement_en": "Xu Shaochun founded Kingdee in 1993; K3 ERP in 1999; HKEX listing 2001; later cloud ERP — half of China's domestic ERP duopoly",
        "still_missing_zh": "大型央企集团级核心 ERP 替代仍处标杆试点阶段；全球化财务合规弱于 Oracle/SAP",
        "still_missing_en": "SOE tier-1 core ERP substitution still in pilot phase; global finance compliance trails Oracle/SAP",
        "evidence_level": "media",
        "sources": [
            {"url": "https://www.tmtpost.com/6673229.html", "title": "金蝶发展历程", "accessed": "2026-06"},
        ],
        "confidence": 0.86,
        "related_policy_ids": [],
    },
    {
        "id": "caxa-eboard-97-1997",
        "date": "1997-01",
        "vendor_id": "caxa",
        "category_l2": "CAD",
        "headline_zh": "CAXA 发布国产二维 CAD「电子图板97」",
        "headline_en": "CAXA ships domestic 2D CAD 'Electronic Drawing Board 97'",
        "before_gap_zh": "1990年代国产二维 CAD 多为科研课题成果，缺少可规模商业化的机械行业 CAD 产品",
        "before_gap_en": "1990s domestic 2D CAD was mostly research output without scalable commercial mechanical CAD products",
        "achievement_zh": "北航雷毅团队推出自主二维 CAD 电子图板97；2003年成立数码大方公司，扩展 CAD/PLM/MES 产品线，成为机械等行业应用最广的国产研发设计软件之一",
        "achievement_en": "Beihang team led by Lei Yi shipped Electronic Drawing Board 97; CAXA incorporated 2003 and expanded CAD/PLM/MES — among widest-deployed domestic R&D software in machinery",
        "still_missing_zh": "三维高端曲面、大型装配与自主几何内核仍落后国际 MCAD；PLM 深度弱于 Siemens Teamcenter",
        "still_missing_en": "3D Class-A surfaces, large assemblies, owned geometry kernel still trail international MCAD; PLM depth trails Siemens Teamcenter",
        "evidence_level": "media",
        "sources": [
            {"url": "https://news.qq.com/rain/a/20210622A019U100", "title": "CAXA 发展历程", "accessed": "2026-06"},
        ],
        "confidence": 0.84,
        "related_policy_ids": ["cad-application-program-1992"],
    },
    {
        "id": "zwsoft-founded-1998",
        "date": "1998-08",
        "vendor_id": "zwcad",
        "product_ids": ["zwcad"],
        "category_l2": "CAD",
        "headline_zh": "中望软件成立，专注自主二维 CAD 与几何内核路线",
        "headline_en": "ZWSOFT founded — proprietary 2D CAD and geometry-kernel path",
        "before_gap_zh": "1990年代末国产 CAD 仍以二维为主，三维几何内核几乎全部依赖 ACIS/Parasolid 授权",
        "before_gap_en": "Late 1990s domestic CAD was mostly 2D; 3D geometry kernels almost entirely licensed from ACIS/Parasolid",
        "achievement_zh": "1998年8月24日成立的中望软件专注自主二维 CAD，2004年起出口海外，后扩展三维 CAD/CAM/CAE；2021年成为 A 股首家研发设计类工业软件上市公司",
        "achievement_en": "Founded 24 Aug 1998, ZWSOFT focused on proprietary 2D CAD, exported from 2004, added 3D CAD/CAM/CAE; 2021 STAR Market first R&D-design industrial software issuer",
        "still_missing_zh": "大型装配、曲面 A 级质量、海外 tier-1 OEM 渗透仍有限",
        "still_missing_en": "Large assemblies, Class-A surfaces, overseas tier-1 OEM penetration still limited",
        "evidence_level": "audited",
        "sources": [
            {"url": "https://static.sse.com.cn/stock/disclosure/announcement/c/202102/000392_20210202_3HRH.pdf", "title": "中望软件招股说明书", "accessed": "2026-06"},
        ],
        "confidence": 0.92,
        "related_policy_ids": [],
    },
    {
        "id": "glodon-founded-1998",
        "date": "1998-08",
        "vendor_id": "glodon",
        "product_ids": ["glodon-bim"],
        "category_l2": "BIM",
        "headline_zh": "广联达成立，从工程造价 DOS 软件起步的建筑数字化龙头",
        "headline_en": "Glodon founded — AEC digitization leader from DOS costing tools",
        "before_gap_zh": "1990年代建筑业造价与工程量计算依赖手工定额，缺少国产化工程计价软件平台",
        "before_gap_en": "1990s construction costing relied on manual quota tables without domestic engineering-pricing software platforms",
        "achievement_zh": "1998年成立的广联达从工程造价 DOS 软件起步，逐步扩展施工管理与 BIM 正向设计，后自研 GDMP/GGP 图形平台，成为中国建筑行业数字造价/BIM 国产化核心厂商",
        "achievement_en": "Glodon founded 1998 with DOS costing tools, expanded to construction management and BIM authoring, later built GDMP/GGP graphics platform — core to domestic AEC digitization",
        "still_missing_zh": "超大型基建多专业实时协同、国际 IFC 互操作深度仍弱于 Revit+Bentley 组合",
        "still_missing_en": "Mega-infrastructure multi-discipline realtime collab and deep IFC interoperability still trail Revit+Bentley stacks",
        "evidence_level": "case_study",
        "sources": [
            {"url": "https://www.glodon.com/history.html", "title": "广联达发展历程", "accessed": "2026-06"},
        ],
        "confidence": 0.9,
        "related_policy_ids": [],
    },
    {
        "id": "empyrean-founded-2009",
        "date": "2009-06",
        "vendor_id": "empyrean",
        "category_l2": "EDA",
        "headline_zh": "华大九天成立，承接核高基 EDA 课题",
        "headline_en": "Empyrean founded to host 核高基 EDA national projects",
        "before_gap_zh": "2000年代国产 EDA 以科研课题为主，缺少可商业化的全流程设计工具企业",
        "before_gap_en": "2000s domestic EDA was mostly R&D projects without commercial full-flow design tool vendors",
        "achievement_zh": "2009年中国电子华大集团 EDA 事业部改制设立华大九天，注册资本4000万元，承办「先进EDA工具平台开发」等核高基/863 课题，成为本土 EDA 龙头",
        "achievement_en": "Spin-out from China Electronics' EDA division June 2009 with ¥40M capital, hosted 核高基/863 EDA sub-projects — leading domestic EDA vendor",
        "still_missing_zh": "数字实现（布局布线/签核）仍弱于国际三巨头；先进节点量产流片仍以进口 EDA 为主",
        "still_missing_en": "Digital implementation (P&R/signoff) still lags the big three; advanced-node tape-outs still run mostly on imported EDA",
        "evidence_level": "audited",
        "sources": [
            {"url": "https://reportdocs.static.szse.cn/UpFiles/rasinfodisc1/202108/RAS_202108_00017B0736947E3FBBD8FE4CB2E9E83F.pdf", "title": "华大九天招股说明书", "accessed": "2026-06"},
        ],
        "confidence": 0.91,
        "related_policy_ids": ["hegaoji-launch-2008"],
    },
    {
        "id": "cad-application-rollout-2000",
        "date": "2000-12",
        "vendor_id": "caxa",
        "category_l2": "CAD",
        "headline_zh": "CAD 应用工程「九五」验收：近10万家企业普及 CAD",
        "headline_en": "National CAD Application Program 9th FYP review: ~100k plants adopt CAD",
        "before_gap_zh": "1990年代初多数设计院与制造企业仍依赖手工绘图板，CAD 普及率极低",
        "before_gap_en": "Early 1990s most design institutes and plants still used manual drafting boards with very low CAD adoption",
        "achievement_zh": "科技部「九五」验收口径：600余家示范企业、3000余家推广企业、近10万家企业普及 CAD；国产 CAXA、开目等与外资 AutoCAD 并存规模化落地",
        "achievement_en": "MOST 9th FYP review: 600+ demo plants, 3,000+ rollout plants, ~100k plants adopted CAD; domestic CAXA/Kaiming alongside AutoCAD at scale",
        "still_missing_zh": "三维 MCAD 与 PLM 集成仍远未普及；高端装备领域仍依赖进口三维 CAD",
        "still_missing_en": "3D MCAD and PLM integration far from universal; high-end equipment still relied on imported 3D CAD",
        "metrics": [
            {"label_zh": "普及企业数", "label_en": "Plants adopted", "value": "~100,000", "verified": True},
        ],
        "evidence_level": "case_study",
        "sources": [
            {"url": "https://www.most.gov.cn/xxgk/xinxifenlei/fdzdgknr/qtwj/qtwj2010before/200312/t20031209_143209.html", "title": "CAD应用工程验收", "accessed": "2026-06"},
        ],
        "confidence": 0.87,
        "related_policy_ids": ["cad-application-program-1992"],
    },
    {
        "id": "big-fund-empyrean-2018",
        "date": "2018-09",
        "vendor_id": "empyrean",
        "category_l2": "EDA",
        "headline_zh": "大基金首次投资华大九天，国家级资本进入国产 EDA 赛道",
        "headline_en": "Big Fund's first bet on Empyrean — national capital enters domestic EDA",
        "before_gap_zh": "国产 EDA 长期依赖核高基课题经费，缺少市场化国家级产业资本背书",
        "before_gap_en": "Domestic EDA relied on 核高基 grants without market-oriented national industrial capital backing",
        "achievement_zh": "2018年9月国家集成电路产业投资基金领投华大九天融资，标志国家级资本正式进入国产 EDA 赛道，形成「政策+基金+课题」三轮驱动",
        "achievement_en": "September 2018 Big Fund led Empyrean financing — first national-capital bet on domestic EDA, completing policy+fund+R&D project drive",
        "still_missing_zh": "大基金投资未自动转化为先进节点客户份额；数字后端工具仍处验证阶段",
        "still_missing_en": "Big Fund investment did not automatically convert to advanced-node customer share; digital backend tools still in validation",
        "evidence_level": "media",
        "sources": [
            {"url": "http://www.chinaaet.com/article/3000089893", "title": "大基金投资华大九天", "accessed": "2026-06"},
        ],
        "confidence": 0.85,
        "related_policy_ids": ["ic-industry-guideline-2014"],
    },
    {
        "id": "empyrean-argus-3dic-2025",
        "date": "2025-05",
        "vendor_id": "empyrean",
        "product_ids": ["empyrean-digital"],
        "category_l2": "EDA",
        "headline_zh": "华大九天发布 Argus 3DIC 物理验证平台，覆盖 Chiplet/2.5D/3D 全流程",
        "headline_en": "Empyrean ships Argus 3DIC PV platform for chiplet / 2.5D / 3D flows",
        "before_gap_zh": "异构集成三维芯片协同设计到 Signoff 长期由 Calibre 等进口工具垄断，国产 EDA 无全流程方案",
        "before_gap_en": "Heterogeneous 3DIC co-design-to-signoff was Calibre-led; no domestic full-flow EDA equivalent",
        "achievement_zh": "公司披露国内唯一覆盖异构集成三维芯片协同设计到 Signoff 的 EDA 方案；3D 数据编织技术宣称验证效率约为传统工具 5 倍，周期从约 2 周缩至 1–2 天",
        "achievement_en": "Vendor claims only domestic full 3DIC co-design-to-signoff flow; 3D data-weaving PV at ~5× efficiency, cycle from ~2 weeks to 1–2 days",
        "still_missing_zh": "竞争声明需客户量产流片验证；数字实现全流程仍弱于 Synopsys/Cadence",
        "still_missing_en": "Competitive claims need customer tape-out validation; full digital implementation still trails Synopsys/Cadence",
        "metrics": [
            {"label_zh": "验证周期", "label_en": "PV cycle", "value": "1–2 days", "verified": False},
        ],
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://finance.sina.com.cn/roll/2026-05-26/doc-inhzfmyq1461474.shtml", "title": "华大九天 Argus 3DIC", "accessed": "2026-06"},
        ],
        "confidence": 0.85,
        "related_policy_ids": [],
    },
    {
        "id": "gstarcad-harmony-2025",
        "date": "2025-05",
        "vendor_id": "gstarcad",
        "product_ids": ["gstarcad"],
        "category_l2": "CAD",
        "headline_zh": "浩辰 CAD 鸿蒙版与鸿蒙电脑同步发布，多终端协同设计",
        "headline_en": "GstarCAD HarmonyOS edition launches with Harmony PC",
        "before_gap_zh": "信创终端缺少原生鸿蒙 CAD，跨端设计文件接续依赖 Windows 虚拟机或 Web 轻量版",
        "before_gap_en": "IT-innovation endpoints lacked native Harmony CAD; cross-device design continuity relied on Windows VMs or lightweight web clients",
        "achievement_zh": "2025-05-19 浩辰 CAD 鸿蒙版与鸿蒙电脑同步亮相，完成电脑/手机/平板多终端适配；依托鸿蒙分布式能力实现跨端文件接续",
        "achievement_en": "2025-05-19 GstarCAD Harmony edition debuts with Harmony PC; multi-terminal coverage with distributed Harmony cross-device file continuity",
        "still_missing_zh": "三维装配、钣金展开、CAM 集成弱于中望/SolidWorks；大企业 PLM 集成案例少",
        "still_missing_en": "3D assembly, sheet-metal, CAM integration trail ZWSOFT/SolidWorks; few enterprise PLM integrations",
        "evidence_level": "media",
        "sources": [
            {"url": "https://m.tech.china.com/articles/20250520/202505201674819.html", "title": "浩辰CAD鸿蒙版发布", "accessed": "2026-06"},
        ],
        "confidence": 0.87,
        "related_policy_ids": ["xinchuang-harmonyos-desktop-ii-2026"],
    },
    {
        "id": "yonyou-bip5-2025",
        "date": "2025-08",
        "vendor_id": "yonyou",
        "product_ids": ["yonyou-bip"],
        "category_l2": "ERP",
        "headline_zh": "用友发布 BIP 5：AI×数据×流程原生一体企业数智平台",
        "headline_en": "Yonyou launches BIP 5 — native AI × data × process enterprise platform",
        "before_gap_zh": "国产高端 ERP 缺乏将 AI 代理、数据湖与业务流程原生融合的统一平台，多依赖外挂式 BI/低代码",
        "before_gap_en": "Domestic tier-1 ERP lacked native fusion of AI agents, data lake, and business processes — relied on bolt-on BI/low-code",
        "achievement_zh": "2025-08 里程碑版本：10 大领域云原生一体；制造云整合智能工厂/MOM/工业大脑/AIoT；全栈信创适配，延续央企高端 ERP 替代叙事",
        "achievement_en": "Aug 2025 milestone: 10-domain cloud-native suite; manufacturing cloud with smart factory/MOM/industrial brain/AIoT; full-stack xinchuang — continues SOE ERP substitution narrative",
        "still_missing_zh": "外部行业复制仍处早期；复杂制造业 MES/PLM 深度集成不如 SAP S/4HANA 成熟生态",
        "still_missing_en": "External industry replication still early; deep MES/PLM integration trails mature SAP S/4HANA ecosystem",
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://www.yonyou.com/subject/yonbip?withYonyouMenu=&zixun=0", "title": "用友 BIP 5", "accessed": "2026-06"},
        ],
        "confidence": 0.84,
        "related_policy_ids": ["miit-erp-xinchuang", "gov-procurement-domestic-20pct"],
    },
    {
        "id": "kingdee-ai-2025",
        "date": "2025-11",
        "vendor_id": "kingdee",
        "product_ids": ["kingdee-cosmic"],
        "category_l2": "ERP",
        "headline_zh": "金蝶「金蝶云」全面升级为「金蝶AI」，发布 AI 星空套件",
        "headline_en": "Kingdee rebrands to 'Kingdee AI' with AI Galaxy suite",
        "before_gap_zh": "国产 SaaS ERP 的 AI 能力多为单点助手，缺少跨财务/供应链/PLM 的统一智能体编排",
        "before_gap_en": "Domestic SaaS ERP AI was mostly point assistants without unified agent orchestration across finance/supply chain/PLM",
        "achievement_zh": "2025-11-04 发布金蝶 AI 星空套件，AI 嵌入财务/供应链/PLM 等 SaaS；172 个高频数据分析场景；2026-05 将发布企业 AI 操作系统「灵基」",
        "achievement_en": "2025-11-04: Kingdee AI Galaxy suite embeds agents in finance/supply chain/PLM SaaS; 172 analytics scenarios; Lingee enterprise AI OS follows 2026-05",
        "still_missing_zh": "AI 操作系统仍处预告阶段；大型集团核心 ERP 替代案例少于用友 BIP",
        "still_missing_en": "AI OS still announced; fewer large-group core ERP substitution cases than Yonyou BIP",
        "metrics": [
            {"label_zh": "数据分析场景", "label_en": "Analytics scenarios", "value": "172", "verified": True},
        ],
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://www.kingdee.com/resources/articles/1437865637112156961", "title": "金蝶AI发布会", "accessed": "2026-06"},
        ],
        "confidence": 0.85,
        "related_policy_ids": ["miit-ai-manufacturing-2027-kpi"],
    },
    {
        "id": "caxa-mega-kernel-2026",
        "date": "2026-03",
        "vendor_id": "caxa",
        "category_l2": "CAD",
        "headline_zh": "数码大方发布 CAXA 2027 与 MEGA Kernel 自主 CAD 几何引擎",
        "headline_en": "CAXA launches 2027 suite and MEGA Kernel owned CAD geometry engine",
        "before_gap_zh": "国产 CAD 厂商长期租赁第三方内核，源代码不可控，高端装备领域存在断供风险",
        "before_gap_en": "Domestic CAD vendors leased third-party kernels without source control — supply-cut risk in high-end equipment",
        "achievement_zh": "2026-03-30 发布会推出 CAD/PLM/MES 2027（新增 500+ 功能）、新一代 MEGA Kernel（多几何表达、工程级精度）及开放 PLM 平台（1000+ API）",
        "achievement_en": "2026-03-30: CAD/PLM/MES 2027 (500+ features), new MEGA Kernel geometry engine, open PLM platform (1000+ APIs) for design–process–manufacturing chain",
        "still_missing_zh": "大型装配性能、国际 OEM 认证案例仍少于 Siemens NX/CATIA",
        "still_missing_en": "Large-assembly performance and international OEM qualifications still trail Siemens NX/CATIA",
        "metrics": [
            {"label_zh": "新增功能", "label_en": "New features", "value": "500+", "verified": True},
        ],
        "evidence_level": "media",
        "sources": [
            {"url": "http://ex.chinadaily.com.cn/exchange/partners/82/rss/channel/cn/columns/sz8srm/stories/WS69cb6ec6a310942cc49a5ca7.html", "title": "CAXA 2027 发布会", "accessed": "2026-06"},
        ],
        "confidence": 0.88,
        "related_policy_ids": ["t-cie-311-cad-security-2025"],
    },
    {
        "id": "glodon-bim2-2026",
        "date": "2026-03",
        "vendor_id": "glodon",
        "product_ids": ["glodon-bim"],
        "category_l2": "BIM",
        "headline_zh": "广联达发布 BIM 2.0 白皮书（DATA+AI 驱动设计–造价–施工一体化）",
        "headline_en": "Glodon releases BIM 2.0 white paper (DATA + AI across design–cost–construction)",
        "before_gap_zh": "BIM 应用长期停留在模型可视化与碰撞检查，缺少构件级数据驱动与 AI 辅助造价/施工闭环",
        "before_gap_en": "BIM adoption stayed at visualization and clash detection without component-level data-driven cost/construction loops",
        "achievement_zh": "2026 工程数智大会发布：BIM 2.0 以 DATA+AI 驱动设计/成本/施工/运维一体化；强调构件级数据、统一交换标准与自主图形平台信创全栈适配",
        "achievement_en": "2026 Engineering Digital Intelligence Congress: BIM 2.0 as DATA+AI across design/cost/construction/O&M; component-level data, open exchange standards, owned graphics on xinchuang stack",
        "still_missing_zh": "超大型基建多专业实时协同、国际 IFC 互操作深度仍弱于 Revit+Bentley",
        "still_missing_en": "Mega-infrastructure multi-discipline realtime collab and deep IFC interoperability still trail Revit+Bentley",
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://compus.glodon.com/news/1582.html", "title": "广联达 BIM 2.0 白皮书", "accessed": "2026-06"},
        ],
        "confidence": 0.86,
        "related_policy_ids": [],
    },
    {
        "id": "zwsoft-wukong-2027-2026",
        "date": "2026-04",
        "vendor_id": "zwcad",
        "product_ids": ["zwcad"],
        "category_l2": "CAD",
        "headline_zh": "中望 2026 年度发布：3D 悟空2027、overdrive® 内核与鸿蒙版",
        "headline_en": "ZWSOFT 2026 launch: 3D Wukong 2027, overdrive® kernel, HarmonyOS 3D",
        "before_gap_zh": "2024 年首次发布 Overdrive 后，高端装备三维 CAD 仍缺新一代产品代际与鸿蒙原生版本",
        "before_gap_en": "After 2024 Overdrive launch, high-end equipment 3D CAD still lacked next product generation and native Harmony edition",
        "achievement_zh": "2026-04-16 上海发布会：云端原生 CAD 365 2.0、高端装备向 3D 悟空2027、自主 overdrive® 内核刷新及中望 3D 鸿蒙版；IDC 连续三年国产研发设计类工业软件市占第一（9.1%，2024 报告）",
        "achievement_en": "2026-04-16 Shanghai launch: cloud-native CAD 365 2.0, Wukong 2027 for high-end equipment, overdrive® refresh, 3D HarmonyOS edition; IDC #1 domestic R&D design ISV three years (9.1% in 2024 report)",
        "still_missing_zh": "大型装配、曲面 A 级质量、与 PLM/MBD 深度集成仍落后 CATIA/NX",
        "still_missing_en": "Large assemblies, Class-A surfaces, deep PLM/MBD integration still trail CATIA/NX",
        "metrics": [
            {"label_zh": "国产研发设计市占", "label_en": "Domestic R&D ISV share", "value": "9.1%", "verified": True},
        ],
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://www.zwsoft.cn/news/291-15822.html", "title": "中望2026年度发布会", "accessed": "2026-06"},
        ],
        "confidence": 0.9,
        "related_policy_ids": ["miit-xinchuang-cad", "xinchuang-harmonyos-desktop-ii-2026"],
    },
    {
        "id": "haitian-x-injection-2026",
        "date": "2026-04",
        "vendor_id": "haitian",
        "category_l2": "MES",
        "headline_zh": "海天国际发布 X-注塑云：端机同源 AI 注塑工艺平台",
        "headline_en": "Haitian International launches X-Injection Cloud AI platform",
        "before_gap_zh": "注塑行业工艺优化依赖老师傅经验与碎片化 APC，缺少与注塑机控制器深度打通的云端 AI 平台",
        "before_gap_en": "Injection molding optimization relied on expert rules and fragmented APC without cloud AI tightly coupled to machine controllers",
        "achievement_zh": "Chinaplas 2026 首发：深度打通注塑机控制器，提供工艺设定/优化/监控全链路；内置 DOE、AI 工艺预测、虚拟调参；2025 年起已在头部家电/汽车/3C 客户落地",
        "achievement_en": "Chinaplas 2026 debut: OEM-coupled edge AI for process set/optimize/monitor; DOE and virtual tuning; production deployments since 2025 in appliance/auto/3C leaders",
        "still_missing_zh": "平台开放生态与第三方 MES 互操作仍弱；海外市场软件收入占比低",
        "still_missing_en": "Open ecosystem and third-party MES interoperability still weak; low overseas software revenue share",
        "evidence_level": "vendor_claim",
        "sources": [
            {"url": "https://haitianpm.com/2026/04/20/haitian-officially-introduces-x-injection/", "title": "海天 X-注塑云", "accessed": "2026-06"},
        ],
        "confidence": 0.88,
        "related_policy_ids": ["miit-ai-manufacturing-2027-kpi"],
    },
    {
        "id": "hoteam-ipo-2026",
        "date": "2026-01",
        "vendor_id": "hoteam",
        "product_ids": ["crowncad"],
        "category_l2": "CAD",
        "headline_zh": "华天软件启动 IPO 辅导备案（中金公司辅导）",
        "headline_en": "Huatian Software files IPO tutoring registration (CICC sponsor)",
        "before_gap_zh": "国产 CAD/PLM 龙头长期依赖私募融资，缺少公开市场估值与持续融资通道",
        "before_gap_en": "Leading domestic CAD/PLM vendors relied on private rounds without public-market valuation and sustained funding access",
        "achievement_zh": "2025-12-29 证监会披露辅导备案；自主 3D 几何引擎与 CrownCAD 云 CAD、SView 生态；累计 9 轮融资，C 轮近 4 亿元（2022）后迈向公开市场",
        "achievement_en": "CSRC tutoring filed 2025-12-29; owned 3D engine, CrownCAD cloud CAD, SView ecosystem; nine funding rounds — path to public market after ~¥400M Series C (2022)",
        "still_missing_zh": "IPO 尚未过会；云 CAD 插件生态、离线大型装配性能仍弱于 SolidWorks/Onshape",
        "still_missing_en": "IPO not yet approved; cloud CAD plugin ecosystem and offline large-assembly performance still trail SolidWorks/Onshape",
        "evidence_level": "case_study",
        "sources": [
            {"url": "http://www.sdenews.com/html/2026/1/380991.shtml", "title": "华天软件IPO辅导备案", "accessed": "2026-06"},
        ],
        "confidence": 0.91,
        "related_policy_ids": [],
    },
    {
        "id": "blacklake-series-d-2026",
        "date": "2026-04",
        "vendor_id": "blacklake",
        "category_l2": "MES",
        "headline_zh": "黑湖科技完成近10亿元 D 轮融资，投后估值超70亿元",
        "headline_en": "Black Lake Tech closes ~¥1B Series D at >¥7B post-money valuation",
        "before_gap_zh": "离散制造云 MES 长期由外资与项目制厂商主导，国产 SaaS MES 缺乏百亿级估值标杆",
        "before_gap_en": "Discrete cloud MES was foreign and project-led; domestic SaaS MES lacked ¥10B+ valuation benchmarks",
        "achievement_zh": "2026-04-23 官宣：资金用于工业 AI 与制造场景融合、AI 原生制造操作系统；宣称中国云化生产管理软件市占 52.7%，服务近 4 万家客户",
        "achievement_en": "2026-04-23: funding for industrial AI + AI-native manufacturing OS; claims 52.7% China cloud production-management share, ~40k customers",
        "still_missing_zh": "市占数据为厂商口径；汽车/半导体高端离散 MES 仍由西门子/SAP 主导",
        "still_missing_en": "Market-share figure is vendor-sourced; auto/semiconductor high-end discrete MES still Siemens/SAP-led",
        "metrics": [
            {"label_zh": "D轮融资", "label_en": "Series D", "value": "~¥10亿", "verified": True},
            {"label_zh": "投后估值", "label_en": "Post-money", "value": ">¥70亿", "verified": True},
        ],
        "evidence_level": "media",
        "sources": [
            {"url": "https://news.qq.com/rain/a/20260423A07H9H00", "title": "黑湖科技D轮融资", "accessed": "2026-06"},
        ],
        "confidence": 0.82,
        "related_policy_ids": ["miit-ai-manufacturing-2027-kpi"],
    },
]


def strip_policy(p: dict) -> dict:
    return {k: v for k, v in p.items() if k not in STRIP_POLICY_KEYS}


def merge_policies() -> tuple[int, list[str]]:
    data = json.loads(POLICIES_PATH.read_text(encoding="utf-8"))
    existing_ids = {p["id"] for p in data["policies"]}
    skipped = []
    added = 0

    for p in PRE2022_POLICIES + POLICY_2025_2026:
        pid = p["id"]
        if pid in existing_ids:
            skipped.append(pid)
            continue
        data["policies"].append(strip_policy(p))
        existing_ids.add(pid)
        added += 1

    # 十四五 as footnote only (duplicates miit-* entries)
    footnote_14th = {
        "date": "2021-11",
        "text_zh": "《「十四五」软件和信息技术服务业发展规划》专章部署工业软件补短板（CAD/CAE/EDA/PLC/DCS/MES），量化 KPI 见上方 miit-software-revenue-14tn 等节点。",
        "text_en": "MIIT 14th Five-Year software plan dedicates a section to industrial software short boards; quantitative KPIs are listed in miit-software-revenue-14tn and related nodes above.",
        "source_url": "https://www.miit.gov.cn/jgsj/xxjsfzs/zlgh/art/2021/art_049186d493524ff6a52971dd9a9d043e.html",
    }
    if not any(f.get("date") == "2021-11" and "十四五" in f.get("text_zh", "") for f in data.get("footnotes", [])):
        data.setdefault("footnotes", []).append(footnote_14th)

    POLICIES_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return added, skipped


def merge_breakthroughs() -> tuple[int, list[str]]:
    data = json.loads(BREAKTHROUGHS_PATH.read_text(encoding="utf-8"))
    existing_ids = {m["id"] for m in data["milestones"]}
    skipped = []
    added = 0

    for m in NEW_MILESTONES:
        m = dict(m)
        normalize_milestone_source_contract(m)
        mid = m["id"]
        if mid in existing_ids:
            skipped.append(mid)
            continue
        data["milestones"].append(m)
        existing_ids.add(mid)
        added += 1

    data["milestones"].sort(key=lambda x: x["date"])
    BREAKTHROUGHS_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return added, skipped


def main() -> None:
    p_added, p_skip = merge_policies()
    b_added, b_skip = merge_breakthroughs()
    print(f"policies added: {p_added}, skipped: {p_skip}")
    print(f"breakthroughs added: {b_added}, skipped: {b_skip}")


if __name__ == "__main__":
    main()
