#!/usr/bin/env python3
"""Emit V1 atlas JSON from the 2026-08 research brief.

Numbers that look precise (2025 city output) are stored as vehicle counts with
explicit statistical_scope + compilation source — they are NOT a unified NBS ranking.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "assets" / "data"

LV = "2026-08"
SRC_COMP = "src-output-compilation-2025"
SRC_BRIEF = "src-research-brief-2026-08"
SRC_YRD = "src-ndrc-yrd-collab"
SRC_CHENGYU = "src-chengyu-2024-cluster"
SRC_MEDIA = "src-media-public-addresses"


def dump(name: str, obj: dict) -> None:
    path = DATA / name
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


def srcs(*ids: str) -> list[str]:
    return list(ids)


CITIES = [
    dict(
        id="beijing", name_zh="北京", name_en="Beijing",
        province_zh="北京市", province_en="Beijing Municipality",
        admin_level="municipality", admin_code="110000", lat=39.9042, lng=116.4074, tier="core",
        summary_zh="全国汽车总部、智能化、标准和媒体中心。官方产业规划将经开区、顺义、房山、昌平、怀柔和密云列为主要汽车产业承载区。",
        summary_en="National auto HQ, intelligence, standards and media hub. Official plans name BDA, Shunyi, Fangshan, Changping, Huairou and Miyun as main auto-industry zones.",
        history_summary_zh="从计划经济时期的整车试制与零部件配套，转向总部、软件、自动驾驶与标准制定。产量不代表北京的全部汽车实力。",
        history_summary_en="Shifted from planned-era assembly toward HQ, software, autonomous driving and standards. Output does not capture Beijing's full auto weight.",
        role_tags=["headquarters", "auto_software", "autonomous_driving", "chips", "testing", "higher_education", "auto_media", "oem_manufacturing"],
        cluster_ids=["jingjinji"],
        districts_zh=["经开区", "顺义", "房山", "昌平", "怀柔", "密云"],
        districts_en=["Beijing Economic-Technological Development Area", "Shunyi", "Fangshan", "Changping", "Huairou", "Miyun"],
    ),
    dict(
        id="shanghai", name_zh="上海", name_en="Shanghai",
        province_zh="上海市", province_en="Shanghai Municipality",
        admin_level="municipality", admin_code="310000", lat=31.2304, lng=121.4737, tier="core",
        summary_zh="综合汽车中心和国际汽车产业窗口：整车、零部件、软件、测试认证、汽车会展和国际合作并存。",
        summary_en="A full-stack auto centre and international window: vehicles, parts, software, testing, auto shows and cross-border cooperation.",
        history_summary_zh="中国最早的轿车工业基地之一。嘉定上海国际汽车城与临港特斯拉超级工厂把总部、测试和大规模制造叠在同一座城市。",
        history_summary_en="One of China's earliest passenger-car bases. Jiading's International Auto City and the Tesla Gigafactory stack HQ, testing and mass manufacturing in one city.",
        role_tags=["headquarters", "oem_manufacturing", "parts", "auto_software", "chips", "testing", "expo_culture", "export_logistics", "higher_education", "auto_media"],
        cluster_ids=["yangtze-river-delta"],
        districts_zh=["嘉定", "临港", "浦东", "安亭"],
        districts_en=["Jiading", "Lingang", "Pudong", "Anting"],
    ),
    dict(
        id="shenzhen", name_zh="深圳", name_en="Shenzhen",
        province_zh="广东省", province_en="Guangdong",
        admin_level="prefecture", admin_code="440300", lat=22.5431, lng=114.0579, tier="core",
        summary_zh="新能源总部、汽车电子、软件和出口中心。官方规划明确区分深汕整车制造与南山、宝安、坪山、龙岗的研发和产业功能。",
        summary_en="NEV headquarters, auto-electronics, software and export hub. Official plans split Shenshan vehicle manufacturing from Nanshan, Bao'an, Pingshan and Longgang R&D.",
        history_summary_zh="比亚迪总部位于深圳，但大量整车在西安、合肥、郑州、长沙、济南、常州和深汕等地生产。把产量记在深圳会严重高估其制造份额。",
        history_summary_en="BYD is headquartered in Shenzhen, but much of its vehicle output sits in Xi'an, Hefei, Zhengzhou, Changsha, Jinan, Changzhou and Shenshan. Booking that output to Shenzhen overstates its plants.",
        role_tags=["headquarters", "battery", "auto_electronics", "auto_software", "autonomous_driving", "export_logistics", "rd_design"],
        cluster_ids=["greater-bay-area"],
        districts_zh=["南山", "宝安", "坪山", "龙岗", "深汕特别合作区"],
        districts_en=["Nanshan", "Bao'an", "Pingshan", "Longgang", "Shenshan Special Cooperation Zone"],
    ),
    dict(
        id="guangzhou", name_zh="广州", name_en="Guangzhou",
        province_zh="广东省", province_en="Guangdong",
        admin_level="prefecture", admin_code="440100", lat=23.1291, lng=113.2644, tier="core",
        summary_zh="多品牌整车制造、自动驾驶、会展和汽车媒体中心。产业空间覆盖番禺、南沙、花都、黄埔和增城。",
        summary_en="Multi-brand vehicle manufacturing plus autonomous driving, auto shows and auto media. Industry space spans Panyu, Nansha, Huadu, Huangpu and Zengcheng.",
        history_summary_zh="日系合资长期主导乘用车产量；广汽埃安与小鹏把新能源和自动驾驶叠进同一座制造型城市。",
        history_summary_en="Japanese JVs long dominated passenger-car output; GAC Aion and XPENG folded NEVs and autonomy into the same manufacturing city.",
        role_tags=["oem_manufacturing", "headquarters", "autonomous_driving", "expo_culture", "auto_media", "higher_education"],
        cluster_ids=["greater-bay-area"],
        districts_zh=["番禺", "南沙", "花都", "黄埔", "增城"],
        districts_en=["Panyu", "Nansha", "Huadu", "Huangpu", "Zengcheng"],
    ),
    dict(
        id="chongqing", name_zh="重庆", name_en="Chongqing",
        province_zh="重庆市", province_en="Chongqing Municipality",
        admin_level="municipality", admin_code="500000", lat=29.5630, lng=106.5516, tier="core",
        summary_zh="大规模整车制造和智能网联转型中心。多家整车企业、大量零部件企业和正在增长的汽车软件集群并存。",
        summary_en="A large-scale vehicle-manufacturing and intelligent-connected transition hub, with multiple OEMs, a dense parts base and a growing auto-software cluster.",
        history_summary_zh="长安体系与兵工转产塑造了西南最大的乘用车和商用车基地之一；2025年地方统计拼合产量居全国城市前列。",
        history_summary_en="Changan and the defence-to-civilian conversion built one of the southwest's largest passenger- and commercial-vehicle bases. Compiled 2025 local output ranks among the top cities.",
        role_tags=["oem_manufacturing", "headquarters", "parts", "auto_software", "testing", "higher_education"],
        cluster_ids=["chengyu"],
        districts_zh=["两江新区", "渝北", "江北", "巴南"],
        districts_en=["Liangjiang New Area", "Yubei", "Jiangbei", "Banan"],
    ),
    dict(
        id="hefei", name_zh="合肥", name_en="Hefei",
        province_zh="安徽省", province_en="Anhui",
        admin_level="prefecture", admin_code="340100", lat=31.8206, lng=117.2272, tier="core",
        summary_zh="新能源整车增长最快的综合节点之一。江淮、蔚来、大众安徽、比亚迪、长安与国轩高科同城布局。",
        summary_en="One of the fastest-growing NEV manufacturing nodes: JAC, NIO, Volkswagen Anhui, BYD, Changan and Gotion share the city.",
        history_summary_zh="从江淮商用车和乘用车基地，叠加蔚来中国总部制造与比亚迪新基地后，2025年汽车与新能源汽车产量均位于全国前列。",
        history_summary_en="A JAC commercial/passenger base that absorbed NIO manufacturing and a BYD plant; 2025 auto and NEV output both rank nationally among the leaders.",
        role_tags=["oem_manufacturing", "headquarters", "battery", "higher_education"],
        cluster_ids=["yangtze-river-delta"],
        districts_zh=["经开区", "新站", "肥西"],
        districts_en=["Economic Development Area", "Xinzhan", "Feixi"],
    ),
    dict(
        id="wuhu", name_zh="芜湖", name_en="Wuhu",
        province_zh="安徽省", province_en="Anhui",
        admin_level="prefecture", admin_code="340200", lat=31.3528, lng=118.4331, tier="core",
        summary_zh="奇瑞主导的全球化整车与供应链城市，围绕发动机、变速箱、出口体系和本地零部件集群展开。",
        summary_en="A Chery-centred global vehicle and supply-chain city: engines, transmissions, export systems and a local parts cluster.",
        history_summary_zh="奇瑞从地方项目成长为出口导向整车集团，芜湖因此成为少有的“一企主导、产量全国前列”的地级市样本。",
        history_summary_en="Chery grew from a local project into an export-oriented OEM, making Wuhu a rare prefecture-level city whose output ranks nationally on one group.",
        role_tags=["oem_manufacturing", "headquarters", "parts", "export_logistics"],
        cluster_ids=["yangtze-river-delta"],
        districts_zh=["经济技术开发区"],
        districts_en=["Wuhu Economic & Technological Development Area"],
    ),
    dict(
        id="xian", name_zh="西安", name_en="Xi'an",
        province_zh="陕西省", province_en="Shaanxi",
        admin_level="prefecture", admin_code="610100", lat=34.3416, lng=108.9398, tier="core",
        summary_zh="比亚迪大规模制造与西北汽车教育节点。2025年主要产量来自比亚迪和吉利，新能源汽车占比较高。",
        summary_en="BYD's large-scale manufacturing node and a northwest auto-education hub. 2025 output is mainly BYD and Geely, with a high NEV share.",
        history_summary_zh="军工和商用车遗产之上，比亚迪西安基地把西北城市推入全国产量第一梯队。",
        history_summary_en="On a defence and commercial-vehicle legacy, BYD's Xi'an base pushed the city into the national output first tier.",
        role_tags=["oem_manufacturing", "higher_education", "battery"],
        cluster_ids=["northwest"],
        districts_zh=["高新区", "经开区"],
        districts_en=["High-tech Zone", "Economic Development Area"],
    ),
    dict(
        id="changchun", name_zh="长春", name_en="Changchun",
        province_zh="吉林省", province_en="Jilin",
        admin_level="prefecture", admin_code="220100", lat=43.8171, lng=125.3235, tier="core",
        summary_zh="中国汽车工业历史核心和一汽总部城市。历史、制造、研发和汽车文化均适合重点呈现。",
        summary_en="Historical core of China's auto industry and FAW headquarters. History, manufacturing, R&D and auto culture all belong on the city page.",
        history_summary_zh="第一汽车制造厂1950年代在此建厂，红旗、解放、一汽-大众构成中国最长的整车谱系之一。",
        history_summary_en="FAW was founded here in the 1950s. Hongqi, Jiefang and FAW-Volkswagen form one of China's longest vehicle lineages.",
        role_tags=["oem_manufacturing", "headquarters", "auto_history", "higher_education", "expo_culture", "rd_design"],
        cluster_ids=["northeast"],
        districts_zh=["汽车经济技术开发区", "绿园"],
        districts_en=["Automobile Economic & Technological Development Area", "Lvyuan"],
    ),
    dict(
        id="zhengzhou", name_zh="郑州", name_en="Zhengzhou",
        province_zh="河南省", province_en="Henan",
        admin_level="prefecture", admin_code="410100", lat=34.7466, lng=113.6254, tier="core",
        summary_zh="新能源整车和客车双重中心。比亚迪郑州基地与宇通客车构成乘用车和商用车两条主线。",
        summary_en="A dual NEV-vehicle and coach hub: BYD's Zhengzhou complex and Yutong form the passenger and commercial spines.",
        history_summary_zh="从客车出口和日产品牌，转向比亚迪综合制造基地后，产量跃入全国前列。",
        history_summary_en="Coach exports and the Nissan marque gave way to a BYD integrated manufacturing base, lifting output into the national top tier.",
        role_tags=["oem_manufacturing", "export_logistics"],
        cluster_ids=["central-plains"],
        districts_zh=["经开区", "航空港"],
        districts_en=["Economic Development Area", "Airport Economy Zone"],
    ),
    dict(
        id="liuzhou", name_zh="柳州", name_en="Liuzhou",
        province_zh="广西壮族自治区", province_en="Guangxi",
        admin_level="prefecture", admin_code="450200", lat=24.3264, lng=109.4281, tier="core",
        summary_zh="小型车、商用车和本地汽车文化城市。四家主要整车生产主体和数百家新能源汽车及零部件企业。",
        summary_en="A small-car, commercial-vehicle and local auto-culture city, with four main vehicle producers and hundreds of NEV and parts firms.",
        history_summary_zh="五菱微型车和东风柳汽商用车把一座工业城市塑造成“车城”认同。",
        history_summary_en="Wuling minicars and Dongfeng Liuzhou trucks turned an industrial city into a self-identified auto town.",
        role_tags=["oem_manufacturing", "parts", "auto_history", "expo_culture"],
        cluster_ids=["guangxi"],
        districts_zh=["柳东", "阳和"],
        districts_en=["Liudong", "Yanghe"],
    ),
    dict(
        id="wuhan", name_zh="武汉", name_en="Wuhan",
        province_zh="湖北省", province_en="Hubei",
        admin_level="prefecture", admin_code="420100", lat=30.5928, lng=114.3055, tier="core",
        summary_zh="东风体系、乘用车和智能网联中心。武汉经开区（中国车谷）聚集整车工厂、供应链和产业平台。",
        summary_en="Dongfeng system, passenger cars and intelligent-connected hub. Wuhan Economic & Technological Development Area (China Auto Valley) hosts plants, suppliers and platforms.",
        history_summary_zh="二汽总部东迁武汉后，车谷成为乘用车、新能源和智能网联的湖北轴线起点。",
        history_summary_en="After Dongfeng's HQ moved east to Wuhan, Auto Valley became the Hubei axis starting point for passenger cars, NEVs and intelligent connectivity.",
        role_tags=["oem_manufacturing", "headquarters", "autonomous_driving", "higher_education", "parts"],
        cluster_ids=["hubei-axis"],
        districts_zh=["武汉经开区", "汉阳"],
        districts_en=["Wuhan Economic & Technological Development Area", "Hanyang"],
    ),
    dict(
        id="changsha", name_zh="长沙", name_en="Changsha",
        province_zh="湖南省", province_en="Hunan",
        admin_level="prefecture", admin_code="430100", lat=28.2282, lng=112.9388, tier="core",
        summary_zh="新能源整车与湖南汽车产业轴核心。页面还应关联株洲的新能源商用车和湘潭的吉利体系。",
        summary_en="NEV manufacturing core of the Hunan auto axis. Later pages should link Zhuzhou NEV commercial vehicles and Xiangtan's Geely system.",
        history_summary_zh="比亚迪、上汽大众、广汽埃安和北汽福田把长沙推成中部新能源整车节点。",
        history_summary_en="BYD, SAIC Volkswagen, GAC Aion and BAIC Foton made Changsha a central-China NEV vehicle node.",
        role_tags=["oem_manufacturing", "higher_education"],
        cluster_ids=["hunan-axis"],
        districts_zh=["经开区", "雨花"],
        districts_en=["Economic Development Area", "Yuhua"],
    ),
    dict(
        id="tianjin", name_zh="天津", name_en="Tianjin",
        province_zh="天津市", province_en="Tianjin Municipality",
        admin_level="municipality", admin_code="120000", lat=39.3434, lng=117.3616, tier="core",
        summary_zh="整车生产、检测认证和行业标准中心。天津经开区承担天津大部分汽车产量，并主办泰达汽车论坛。",
        summary_en="Vehicle production, testing/certification and industry-standards centre. TEDA accounts for most of Tianjin's output and hosts the TEDA Auto Forum.",
        history_summary_zh="港口城市叠加一汽丰田、一汽-大众和长城产能，并以中汽中心掌握检测与标准话语权。",
        history_summary_en="A port city stacking FAW Toyota, FAW-Volkswagen and GWM capacity, with CATARC holding testing and standards authority.",
        role_tags=["oem_manufacturing", "testing", "expo_culture", "export_logistics"],
        cluster_ids=["jingjinji"],
        districts_zh=["天津经开区", "西青"],
        districts_en=["Tianjin Economic-Technological Development Area", "Xiqing"],
    ),
    dict(
        id="chengdu", name_zh="成都", name_en="Chengdu",
        province_zh="四川省", province_en="Sichuan",
        admin_level="prefecture", admin_code="510100", lat=30.5728, lng=104.0668, tier="core",
        summary_zh="西南整车生产和成渝供应链节点。与重庆、宜宾之间存在整车、零部件和动力电池协作。",
        summary_en="Southwest vehicle production and a Chengdu–Chongqing supply node, collaborating with Chongqing and Yibin on vehicles, parts and batteries.",
        history_summary_zh="一汽-大众、一汽丰田、沃尔沃与吉利/领克相关基地把成都经开区做成西南乘用车第二中心。",
        history_summary_en="FAW-Volkswagen, FAW Toyota, Volvo and Geely/Lynk & Co plants made Chengdu's development area the southwest's second passenger-car centre.",
        role_tags=["oem_manufacturing", "parts"],
        cluster_ids=["chengyu"],
        districts_zh=["成都经开区", "龙泉驿"],
        districts_en=["Chengdu Economic Development Area", "Longquanyi"],
    ),
    dict(
        id="ningde", name_zh="宁德", name_en="Ningde",
        province_zh="福建省", province_en="Fujian",
        admin_level="prefecture", admin_code="350900", lat=26.6655, lng=119.5480, tier="specialist",
        summary_zh="动力电池总部和产业集群。宁德时代已形成跨城市、跨国生产和研发网络。",
        summary_en="Power-battery headquarters and industrial cluster. CATL already runs a cross-city and cross-border manufacturing and R&D network.",
        history_summary_zh="一座原本不以整车见长的东部地级市，因动力电池成为全球汽车供应链关键节点。",
        history_summary_en="An eastern prefecture that was never an OEM city became a global auto-supply node through power batteries.",
        role_tags=["battery", "headquarters", "rd_design"],
        cluster_ids=["battery-corridor"],
        districts_zh=["蕉城", "福鼎", "霞浦"],
        districts_en=["Jiaocheng", "Fuding", "Xiapu"],
    ),
    dict(
        id="changzhou", name_zh="常州", name_en="Changzhou",
        province_zh="江苏省", province_en="Jiangsu",
        admin_level="prefecture", admin_code="320400", lat=31.8107, lng=119.9741, tier="specialist",
        summary_zh="新能源整车与动力电池高度集聚：理想汽车、比亚迪、江苏时代、蜂巢能源、中创新航及大量零部件企业。",
        summary_en="Dense NEV vehicles and batteries: Li Auto, BYD, CATL Jiangsu, SVOLT, CALB and a large parts base.",
        history_summary_zh="在长三角协作中常被点名为动力电池节点，同时承接理想和比亚迪整车。",
        history_summary_en="Named in Yangtze Delta collaboration cases as a battery node, while also hosting Li Auto and BYD vehicle plants.",
        role_tags=["oem_manufacturing", "battery", "parts"],
        cluster_ids=["yangtze-river-delta", "battery-corridor"],
        districts_zh=["金坛", "武进", "经开区"],
        districts_en=["Jintan", "Wujin", "Economic Development Area"],
    ),
    dict(
        id="suzhou", name_zh="苏州", name_en="Suzhou",
        province_zh="江苏省", province_en="Jiangsu",
        admin_level="prefecture", admin_code="320500", lat=31.2989, lng=120.5853, tier="specialist",
        summary_zh="汽车电子、零部件、智能网联测试和出口。太仓德系零部件集群与太仓港汽车出口是跨城市网络的典型接口。",
        summary_en="Auto electronics, parts, intelligent-connected testing and export. Taicang's German parts cluster and auto export port are typical cross-city interfaces.",
        history_summary_zh="不靠整车厂定义自己，而靠给上海和长三角整车配套。",
        history_summary_en="Defines itself by supplying Shanghai and Yangtze Delta OEMs rather than by hosting a flagship plant.",
        role_tags=["auto_electronics", "parts", "testing", "export_logistics"],
        cluster_ids=["yangtze-river-delta"],
        districts_zh=["工业园区", "太仓", "昆山"],
        districts_en=["Suzhou Industrial Park", "Taicang", "Kunshan"],
    ),
    dict(
        id="ningbo", name_zh="宁波", name_en="Ningbo",
        province_zh="浙江省", province_en="Zhejiang",
        admin_level="prefecture", admin_code="330200", lat=29.8683, lng=121.5440, tier="specialist",
        summary_zh="全球化零部件公司集群：均胜电子、拓普集团、敏实集团、华翔集团及大量规模以上汽车企业。",
        summary_en="A cluster of globalising parts groups: Joyson, Tuopu, Minth, Huaxiang and many above-scale auto firms.",
        history_summary_zh="国家发展改革委区域资料将宁波整车制造与上海软件芯片、常州动力电池并列为长三角协作案例。",
        history_summary_en="NDRC regional materials cite Ningbo vehicle manufacturing alongside Shanghai software/chips and Changzhou batteries as a Yangtze Delta collaboration case.",
        role_tags=["parts", "auto_electronics", "oem_manufacturing", "export_logistics"],
        cluster_ids=["yangtze-river-delta"],
        districts_zh=["杭州湾", "北仑", "慈溪"],
        districts_en=["Hangzhou Bay", "Beilun", "Cixi"],
    ),
    dict(
        id="huizhou", name_zh="惠州", name_en="Huizhou",
        province_zh="广东省", province_en="Guangdong",
        admin_level="prefecture", admin_code="441300", lat=23.1115, lng=114.4162, tier="specialist",
        summary_zh="汽车电子、智能座舱和动力电池。德赛西威、华阳集团、亿纬锂能与深圳、广州形成电子与零部件协作。",
        summary_en="Auto electronics, smart cockpit and batteries. Desay SV, Holosonics/HuaYang and EVE Energy collaborate with Shenzhen and Guangzhou.",
        history_summary_zh="湾区电子制造外溢，使惠州成为座舱域控制器和电池的专业城市。",
        history_summary_en="Bay Area electronics overflow made Huizhou a specialist city for cockpit domain controllers and batteries.",
        role_tags=["auto_electronics", "battery", "parts"],
        cluster_ids=["greater-bay-area"],
        districts_zh=["仲恺", "惠城"],
        districts_en=["Zhongkai", "Huicheng"],
    ),
    dict(
        id="yibin", name_zh="宜宾", name_en="Yibin",
        province_zh="四川省", province_en="Sichuan",
        admin_level="prefecture", admin_code="511500", lat=28.7518, lng=104.6432, tier="specialist",
        summary_zh="动力电池制造和能源条件城市。四川时代、动力电池产业园与世界动力电池大会构成成渝电池支点。",
        summary_en="Power-battery manufacturing plus energy conditions. CATL Sichuan, the battery park and the World Power Battery Conference form the Chengyu battery pivot.",
        history_summary_zh="水电与工业用地条件吸引宁德时代落地，宜宾因此进入汽车图谱，而不是因为整车厂。",
        history_summary_en="Hydropower and industrial land brought CATL in; Yibin enters the auto atlas through batteries, not OEMs.",
        role_tags=["battery", "expo_culture"],
        cluster_ids=["chengyu", "battery-corridor"],
        districts_zh=["三江新区"],
        districts_en=["Sanjiang New Area"],
    ),
    dict(
        id="baoding", name_zh="保定", name_en="Baoding",
        province_zh="河北省", province_en="Hebei",
        admin_level="prefecture", admin_code="130600", lat=38.8510, lng=115.4900, tier="specialist",
        summary_zh="民营整车总部和完整制造链。长城汽车总部、研发设施、徐水智慧工厂及本地零部件体系。",
        summary_en="A private OEM headquarters with a full manufacturing chain: GWM HQ, R&D, the Xushui smart plant and a local parts system.",
        history_summary_zh="长城从皮卡和SUV起家，使保定成为京津冀整车制造的河北支点。",
        history_summary_en="GWM's pickup and SUV path made Baoding the Hebei vehicle-manufacturing pivot of Jing-Jin-Ji.",
        role_tags=["headquarters", "oem_manufacturing", "rd_design", "parts"],
        cluster_ids=["jingjinji"],
        districts_zh=["徐水", "莲池"],
        districts_en=["Xushui", "Lianchi"],
    ),
    dict(
        id="jinan", name_zh="济南", name_en="Jinan",
        province_zh="山东省", province_en="Shandong",
        admin_level="prefecture", admin_code="370100", lat=36.6512, lng=117.1201, tier="specialist",
        summary_zh="重型商用车与新能源整车。中国重汽、比亚迪、吉利及相关零部件园区。",
        summary_en="Heavy commercial vehicles plus NEV passenger cars: Sinotruk, BYD, Geely and related parts parks.",
        history_summary_zh="重汽体系长期定义济南的商用车身份，比亚迪等新基地把它拉进新能源乘用车版图。",
        history_summary_en="Sinotruk long defined Jinan as a commercial-vehicle city; BYD and others pulled it into NEV passenger cars.",
        role_tags=["oem_manufacturing", "headquarters", "parts"],
        cluster_ids=["shandong"],
        districts_zh=["高新区", "章丘"],
        districts_en=["High-tech Zone", "Zhangqiu"],
    ),
    dict(
        id="shiyan", name_zh="十堰", name_en="Shiyan",
        province_zh="湖北省", province_en="Hubei",
        admin_level="prefecture", admin_code="420300", lat=32.6294, lng=110.7980, tier="specialist",
        summary_zh="中国商用车历史和专业供应链城市。东风商用车、重型与中型商用车工厂、大量专用零部件企业。",
        summary_en="China's commercial-vehicle history city and a specialist supply chain: Dongfeng Commercial Vehicles, medium/heavy plants and dedicated parts firms.",
        history_summary_zh="第二汽车制造厂因备战选址十堰。总部东迁武汉后，十堰仍是中重卡和专用件的历史产地。",
        history_summary_en="Second Auto Works was sited in Shiyan for defence-in-depth. After HQ moved to Wuhan, Shiyan remained the historical home of medium/heavy trucks and specialist parts.",
        role_tags=["oem_manufacturing", "auto_history", "parts"],
        cluster_ids=["hubei-axis"],
        districts_zh=["张湾", "茅箭"],
        districts_en=["Zhangwan", "Maojian"],
    ),
    dict(
        id="xiamen", name_zh="厦门", name_en="Xiamen",
        province_zh="福建省", province_en="Fujian",
        admin_level="prefecture", admin_code="350200", lat=24.4798, lng=118.0894, tier="specialist",
        summary_zh="客车和新能源商用车。金龙客车、金旅客车，以及新能源客车与燃料电池商用车产业。",
        summary_en="Coaches and NEV commercial vehicles: King Long, Golden Dragon, plus NEV buses and fuel-cell commercial vehicles.",
        history_summary_zh="港口城市用客车出口建立全球可见度，而不是用乘用车产量。",
        history_summary_en="A port city that earned global visibility through coach exports rather than passenger-car volume.",
        role_tags=["oem_manufacturing", "export_logistics"],
        cluster_ids=["fujian-bus"],
        districts_zh=["集美", "湖里"],
        districts_en=["Jimei", "Huli"],
    ),
]

for c in CITIES:
    c["featured_entity_ids"] = []
    c["last_verified"] = LV
    c["confidence"] = 0.72 if c["tier"] == "core" else 0.68


def org(**kw):
    row = dict(
        parent_id=None,
        founded_year=None,
        website=None,
        status="active",
        focus_tags=[],
        last_verified=LV,
        confidence=0.7,
        source_ids=srcs(SRC_BRIEF),
    )
    row.update(kw)
    return row


ORGS = [
    org(id="baic", legal_name_zh="北京汽车集团有限公司", legal_name_en="Beijing Automotive Group Co., Ltd.",
        display_name_zh="北汽", display_name_en="BAIC", organization_type="automaker",
        headquarters_city_id="beijing", founded_year=1958, focus_tags=["oem_manufacturing", "headquarters"]),
    org(id="beijing-benz", legal_name_zh="北京奔驰汽车有限公司", legal_name_en="Beijing Benz Automotive Co., Ltd.",
        display_name_zh="北京奔驰", display_name_en="Beijing Benz", organization_type="automaker",
        parent_id="baic", headquarters_city_id="beijing", focus_tags=["oem_manufacturing"]),
    org(id="xiaomi-auto", legal_name_zh="小米汽车", legal_name_en="Xiaomi Auto",
        display_name_zh="小米汽车", display_name_en="Xiaomi Auto", organization_type="automaker",
        headquarters_city_id="beijing", founded_year=2021, focus_tags=["oem_manufacturing", "auto_software"]),
    org(id="li-auto", legal_name_zh="理想汽车", legal_name_en="Li Auto",
        display_name_zh="理想汽车", display_name_en="Li Auto", organization_type="automaker",
        headquarters_city_id="beijing", founded_year=2015, website="https://www.lixiang.com/",
        focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="baidu", legal_name_zh="百度", legal_name_en="Baidu",
        display_name_zh="百度", display_name_en="Baidu", organization_type="software_company",
        headquarters_city_id="beijing", focus_tags=["autonomous_driving", "auto_software"]),
    org(id="horizon-robotics", legal_name_zh="地平线", legal_name_en="Horizon Robotics",
        display_name_zh="地平线", display_name_en="Horizon Robotics", organization_type="chip_company",
        headquarters_city_id="beijing", focus_tags=["chips", "autonomous_driving"]),
    org(id="saic", legal_name_zh="上海汽车集团股份有限公司", legal_name_en="SAIC Motor Corporation Limited",
        display_name_zh="上汽集团", display_name_en="SAIC Motor", organization_type="automaker",
        headquarters_city_id="shanghai", website="https://www.saicmotor.com/", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="tesla-china", legal_name_zh="特斯拉（上海）有限公司", legal_name_en="Tesla (Shanghai) Co., Ltd.",
        display_name_zh="特斯拉上海", display_name_en="Tesla Shanghai", organization_type="automaker",
        headquarters_city_id="shanghai", founded_year=2019, focus_tags=["oem_manufacturing", "export_logistics"]),
    org(id="byd", legal_name_zh="比亚迪股份有限公司", legal_name_en="BYD Company Limited",
        display_name_zh="比亚迪", display_name_en="BYD", organization_type="automaker",
        headquarters_city_id="shenzhen", website="https://www.byd.com/", founded_year=1995,
        focus_tags=["headquarters", "oem_manufacturing", "battery"]),
    org(id="gac", legal_name_zh="广州汽车集团股份有限公司", legal_name_en="Guangzhou Automobile Group Co., Ltd.",
        display_name_zh="广汽集团", display_name_en="GAC Group", organization_type="automaker",
        headquarters_city_id="guangzhou", website="https://www.gac.com.cn/", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="gac-honda", legal_name_zh="广汽本田汽车有限公司", legal_name_en="GAC Honda Automobile Co., Ltd.",
        display_name_zh="广汽本田", display_name_en="GAC Honda", organization_type="automaker",
        parent_id="gac", headquarters_city_id="guangzhou", focus_tags=["oem_manufacturing"]),
    org(id="gac-toyota", legal_name_zh="广汽丰田汽车有限公司", legal_name_en="GAC Toyota Motor Co., Ltd.",
        display_name_zh="广汽丰田", display_name_en="GAC Toyota", organization_type="automaker",
        parent_id="gac", headquarters_city_id="guangzhou", focus_tags=["oem_manufacturing"]),
    org(id="dongfeng-nissan", legal_name_zh="东风汽车有限公司东风日产乘用车公司", legal_name_en="Dongfeng Nissan Passenger Vehicle Company",
        display_name_zh="东风日产", display_name_en="Dongfeng Nissan", organization_type="automaker",
        parent_id="dongfeng", headquarters_city_id="guangzhou", focus_tags=["oem_manufacturing"]),
    org(id="xpeng", legal_name_zh="小鹏汽车", legal_name_en="XPENG",
        display_name_zh="小鹏汽车", display_name_en="XPENG", organization_type="automaker",
        headquarters_city_id="guangzhou", website="https://www.xiaopeng.com/", focus_tags=["oem_manufacturing", "autonomous_driving"]),
    org(id="weiride", legal_name_zh="文远知行", legal_name_en="WeRide",
        display_name_zh="文远知行", display_name_en="WeRide", organization_type="software_company",
        headquarters_city_id="guangzhou", focus_tags=["autonomous_driving"]),
    org(id="pony-ai", legal_name_zh="小马智行", legal_name_en="Pony.ai",
        display_name_zh="小马智行", display_name_en="Pony.ai", organization_type="software_company",
        headquarters_city_id="guangzhou", focus_tags=["autonomous_driving"]),
    org(id="changan", legal_name_zh="重庆长安汽车股份有限公司", legal_name_en="Chongqing Changan Automobile Co., Ltd.",
        display_name_zh="长安汽车", display_name_en="Changan Auto", organization_type="automaker",
        headquarters_city_id="chongqing", website="https://www.changan.com.cn/", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="seres", legal_name_zh="赛力斯集团", legal_name_en="Seres Group",
        display_name_zh="赛力斯", display_name_en="Seres", organization_type="automaker",
        headquarters_city_id="chongqing", focus_tags=["oem_manufacturing"]),
    org(id="qianli", legal_name_zh="千里科技", legal_name_en="Qianli Technology",
        display_name_zh="千里科技", display_name_en="Qianli Technology", organization_type="software_company",
        headquarters_city_id="chongqing", focus_tags=["auto_software"]),
    org(id="jac", legal_name_zh="安徽江淮汽车集团股份有限公司", legal_name_en="Anhui Jianghuai Automobile Group",
        display_name_zh="江淮汽车", display_name_en="JAC", organization_type="automaker",
        headquarters_city_id="hefei", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="nio", legal_name_zh="蔚来", legal_name_en="NIO",
        display_name_zh="蔚来", display_name_en="NIO", organization_type="automaker",
        headquarters_city_id="hefei", website="https://www.nio.com/", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="vw-anhui", legal_name_zh="大众汽车（安徽）有限公司", legal_name_en="Volkswagen (Anhui) Co., Ltd.",
        display_name_zh="大众安徽", display_name_en="Volkswagen Anhui", organization_type="automaker",
        headquarters_city_id="hefei", focus_tags=["oem_manufacturing"]),
    org(id="gotion", legal_name_zh="国轩高科", legal_name_en="Gotion High-tech",
        display_name_zh="国轩高科", display_name_en="Gotion", organization_type="battery_company",
        headquarters_city_id="hefei", focus_tags=["battery"]),
    org(id="chery", legal_name_zh="奇瑞汽车股份有限公司", legal_name_en="Chery Automobile Co., Ltd.",
        display_name_zh="奇瑞汽车", display_name_en="Chery", organization_type="automaker",
        headquarters_city_id="wuhu", website="https://www.cheryinternational.com/", focus_tags=["headquarters", "oem_manufacturing", "export_logistics"]),
    org(id="geely", legal_name_zh="浙江吉利控股集团", legal_name_en="Zhejiang Geely Holding Group",
        display_name_zh="吉利", display_name_en="Geely", organization_type="automaker",
        headquarters_city_id=None, focus_tags=["oem_manufacturing"]),
    org(id="faw", legal_name_zh="中国第一汽车集团有限公司", legal_name_en="China FAW Group Co., Ltd.",
        display_name_zh="中国一汽", display_name_en="FAW", organization_type="automaker",
        headquarters_city_id="changchun", founded_year=1953, website="https://www.faw.com.cn/",
        focus_tags=["headquarters", "oem_manufacturing", "auto_history"]),
    org(id="hongqi", legal_name_zh="一汽红旗", legal_name_en="FAW Hongqi",
        display_name_zh="红旗", display_name_en="Hongqi", organization_type="brand",
        parent_id="faw", headquarters_city_id="changchun", focus_tags=["oem_manufacturing"]),
    org(id="jiefang", legal_name_zh="一汽解放", legal_name_en="FAW Jiefang",
        display_name_zh="解放", display_name_en="Jiefang", organization_type="brand",
        parent_id="faw", headquarters_city_id="changchun", focus_tags=["oem_manufacturing"]),
    org(id="bestune", legal_name_zh="一汽奔腾", legal_name_en="Bestune",
        display_name_zh="奔腾", display_name_en="Bestune", organization_type="brand",
        parent_id="faw", headquarters_city_id="changchun", focus_tags=["oem_manufacturing"]),
    org(id="faw-vw", legal_name_zh="一汽-大众汽车有限公司", legal_name_en="FAW-Volkswagen Automotive Co., Ltd.",
        display_name_zh="一汽-大众", display_name_en="FAW-Volkswagen", organization_type="automaker",
        parent_id="faw", headquarters_city_id="changchun", focus_tags=["oem_manufacturing"]),
    org(id="audi-faw-nev", legal_name_zh="奥迪一汽新能源汽车有限公司", legal_name_en="Audi FAW NEV Co., Ltd.",
        display_name_zh="奥迪一汽新能源", display_name_en="Audi FAW NEV", organization_type="automaker",
        parent_id="faw", headquarters_city_id="changchun", focus_tags=["oem_manufacturing"]),
    org(id="yutong", legal_name_zh="宇通客车股份有限公司", legal_name_en="Yutong Bus Co., Ltd.",
        display_name_zh="宇通客车", display_name_en="Yutong", organization_type="automaker",
        headquarters_city_id="zhengzhou", website="https://en.yutong.com/", focus_tags=["oem_manufacturing", "export_logistics"]),
    org(id="zhengzhou-nissan", legal_name_zh="郑州日产汽车有限公司", legal_name_en="Zhengzhou Nissan Automobile Co., Ltd.",
        display_name_zh="郑州日产", display_name_en="Zhengzhou Nissan", organization_type="automaker",
        headquarters_city_id="zhengzhou", focus_tags=["oem_manufacturing"]),
    org(id="sgmw", legal_name_zh="上汽通用五菱汽车股份有限公司", legal_name_en="SAIC-GM-Wuling Automobile",
        display_name_zh="上汽通用五菱", display_name_en="SGMW", organization_type="automaker",
        parent_id="saic", headquarters_city_id="liuzhou", focus_tags=["oem_manufacturing"]),
    org(id="dongfeng-liuzhou", legal_name_zh="东风柳州汽车有限公司", legal_name_en="Dongfeng Liuzhou Motor Co., Ltd.",
        display_name_zh="东风柳汽", display_name_en="Dongfeng Liuzhou Motor", organization_type="automaker",
        parent_id="dongfeng", headquarters_city_id="liuzhou", focus_tags=["oem_manufacturing"]),
    org(id="guangxi-auto", legal_name_zh="广西汽车集团", legal_name_en="Guangxi Automobile Group",
        display_name_zh="广西汽车集团", display_name_en="Guangxi Auto Group", organization_type="automaker",
        headquarters_city_id="liuzhou", focus_tags=["oem_manufacturing"]),
    org(id="dongfeng", legal_name_zh="东风汽车集团有限公司", legal_name_en="Dongfeng Motor Corporation",
        display_name_zh="东风集团", display_name_en="Dongfeng Motor", organization_type="automaker",
        headquarters_city_id="wuhan", website="https://www.dfmc.com.cn/", focus_tags=["headquarters", "oem_manufacturing", "auto_history"]),
    org(id="voyah", legal_name_zh="岚图汽车", legal_name_en="Voyah",
        display_name_zh="岚图", display_name_en="Voyah", organization_type="brand",
        parent_id="dongfeng", headquarters_city_id="wuhan", focus_tags=["oem_manufacturing"]),
    org(id="mengshi", legal_name_zh="猛士汽车", legal_name_en="Mengshi",
        display_name_zh="猛士", display_name_en="Mengshi", organization_type="brand",
        parent_id="dongfeng", headquarters_city_id="wuhan", focus_tags=["oem_manufacturing"]),
    org(id="aeolus", legal_name_zh="东风奕派", legal_name_en="Aeolus (Voyah family / Dongfeng Aeolus)",
        display_name_zh="奕派", display_name_en="Aeolus", organization_type="brand",
        parent_id="dongfeng", headquarters_city_id="wuhan", focus_tags=["oem_manufacturing"]),
    org(id="faw-toyota", legal_name_zh="一汽丰田", legal_name_en="FAW Toyota",
        display_name_zh="一汽丰田", display_name_en="FAW Toyota", organization_type="automaker",
        parent_id="faw", headquarters_city_id="tianjin", focus_tags=["oem_manufacturing"]),
    org(id="gwm", legal_name_zh="长城汽车股份有限公司", legal_name_en="Great Wall Motor Company Limited",
        display_name_zh="长城汽车", display_name_en="Great Wall Motor", organization_type="automaker",
        headquarters_city_id="baoding", website="https://www.gwm.com.cn/", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="volvo-cars-chengdu", legal_name_zh="沃尔沃汽车成都工厂运营主体", legal_name_en="Volvo Cars Chengdu plant operator",
        display_name_zh="沃尔沃成都", display_name_en="Volvo Chengdu", organization_type="automaker",
        headquarters_city_id="chengdu", focus_tags=["oem_manufacturing"]),
    org(id="catl", legal_name_zh="宁德时代新能源科技股份有限公司", legal_name_en="Contemporary Amperex Technology Co., Limited",
        display_name_zh="宁德时代", display_name_en="CATL", organization_type="battery_company",
        headquarters_city_id="ningde", website="https://www.catl.com/", founded_year=2011,
        focus_tags=["battery", "headquarters"]),
    org(id="svolt", legal_name_zh="蜂巢能源", legal_name_en="SVOLT Energy",
        display_name_zh="蜂巢能源", display_name_en="SVOLT", organization_type="battery_company",
        headquarters_city_id="changzhou", focus_tags=["battery"]),
    org(id="calb", legal_name_zh="中创新航", legal_name_en="CALB",
        display_name_zh="中创新航", display_name_en="CALB", organization_type="battery_company",
        headquarters_city_id="changzhou", focus_tags=["battery"]),
    org(id="desay-sv", legal_name_zh="惠州市德赛西威汽车电子股份有限公司", legal_name_en="Huizhou Desay SV Automotive Co., Ltd.",
        display_name_zh="德赛西威", display_name_en="Desay SV", organization_type="supplier",
        headquarters_city_id="huizhou", focus_tags=["auto_electronics"]),
    org(id="holosonics", legal_name_zh="惠州市华阳集团", legal_name_en="Foryou / HuaYang Group",
        display_name_zh="华阳集团", display_name_en="HuaYang", organization_type="supplier",
        headquarters_city_id="huizhou", focus_tags=["auto_electronics"]),
    org(id="eve-energy", legal_name_zh="亿纬锂能", legal_name_en="EVE Energy",
        display_name_zh="亿纬锂能", display_name_en="EVE Energy", organization_type="battery_company",
        headquarters_city_id="huizhou", focus_tags=["battery"]),
    org(id="joyson", legal_name_zh="均胜电子", legal_name_en="Joyson Electronics",
        display_name_zh="均胜电子", display_name_en="Joyson", organization_type="supplier",
        headquarters_city_id="ningbo", focus_tags=["auto_electronics", "parts"]),
    org(id="tuopu", legal_name_zh="拓普集团", legal_name_en="Tuopu Group",
        display_name_zh="拓普集团", display_name_en="Tuopu", organization_type="supplier",
        headquarters_city_id="ningbo", focus_tags=["parts"]),
    org(id="minth", legal_name_zh="敏实集团", legal_name_en="Minth Group",
        display_name_zh="敏实集团", display_name_en="Minth", organization_type="supplier",
        headquarters_city_id="ningbo", focus_tags=["parts"]),
    org(id="huaxiang", legal_name_zh="华翔集团", legal_name_en="Huaxiang Group",
        display_name_zh="华翔集团", display_name_en="Huaxiang", organization_type="supplier",
        headquarters_city_id="ningbo", focus_tags=["parts"]),
    org(id="sinotruk", legal_name_zh="中国重型汽车集团有限公司", legal_name_en="China National Heavy Duty Truck Group",
        display_name_zh="中国重汽", display_name_en="Sinotruk", organization_type="automaker",
        headquarters_city_id="jinan", focus_tags=["headquarters", "oem_manufacturing"]),
    org(id="king-long", legal_name_zh="厦门金龙联合汽车工业有限公司", legal_name_en="King Long United Automotive Industry Co., Ltd.",
        display_name_zh="金龙客车", display_name_en="King Long", organization_type="automaker",
        headquarters_city_id="xiamen", focus_tags=["oem_manufacturing"]),
    org(id="golden-dragon", legal_name_zh="厦门金龙旅行车有限公司", legal_name_en="Xiamen Golden Dragon Bus Co., Ltd.",
        display_name_zh="金旅客车", display_name_en="Golden Dragon", organization_type="automaker",
        headquarters_city_id="xiamen", focus_tags=["oem_manufacturing"]),
    org(id="catarc", legal_name_zh="中国汽车技术研究中心有限公司", legal_name_en="China Automotive Technology and Research Center",
        display_name_zh="中汽中心", display_name_en="CATARC", organization_type="testing_body",
        headquarters_city_id="tianjin", focus_tags=["testing"]),
    org(id="caeri", legal_name_zh="中国汽车工程研究院股份有限公司", legal_name_en="China Automotive Engineering Research Institute",
        display_name_zh="中国汽研", display_name_en="CAERI", organization_type="research_institute",
        headquarters_city_id="chongqing", focus_tags=["testing", "rd_design"]),
    org(id="tsinghua", legal_name_zh="清华大学", legal_name_en="Tsinghua University",
        display_name_zh="清华大学", display_name_en="Tsinghua University", organization_type="university",
        headquarters_city_id="beijing", website="https://www.tsinghua.edu.cn/", focus_tags=["higher_education"]),
    org(id="bit", legal_name_zh="北京理工大学", legal_name_en="Beijing Institute of Technology",
        display_name_zh="北京理工大学", display_name_en="BIT", organization_type="university",
        headquarters_city_id="beijing", focus_tags=["higher_education"]),
    org(id="tongji", legal_name_zh="同济大学", legal_name_en="Tongji University",
        display_name_zh="同济大学", display_name_en="Tongji University", organization_type="university",
        headquarters_city_id="shanghai", focus_tags=["higher_education"]),
    org(id="sjtu", legal_name_zh="上海交通大学", legal_name_en="Shanghai Jiao Tong University",
        display_name_zh="上海交通大学", display_name_en="SJTU", organization_type="university",
        headquarters_city_id="shanghai", focus_tags=["higher_education"]),
    org(id="jlu", legal_name_zh="吉林大学", legal_name_en="Jilin University",
        display_name_zh="吉林大学", display_name_en="Jilin University", organization_type="university",
        headquarters_city_id="changchun", focus_tags=["higher_education", "auto_history"]),
    org(id="whut", legal_name_zh="武汉理工大学", legal_name_en="Wuhan University of Technology",
        display_name_zh="武汉理工大学", display_name_en="WUT", organization_type="university",
        headquarters_city_id="wuhan", focus_tags=["higher_education"]),
    org(id="hfut", legal_name_zh="合肥工业大学", legal_name_en="Hefei University of Technology",
        display_name_zh="合肥工业大学", display_name_en="HFUT", organization_type="university",
        headquarters_city_id="hefei", focus_tags=["higher_education"]),
    org(id="changan-univ", legal_name_zh="长安大学", legal_name_en="Chang'an University",
        display_name_zh="长安大学", display_name_en="Chang'an University", organization_type="university",
        headquarters_city_id="xian", focus_tags=["higher_education"]),
    org(id="hnu", legal_name_zh="湖南大学", legal_name_en="Hunan University",
        display_name_zh="湖南大学", display_name_en="Hunan University", organization_type="university",
        headquarters_city_id="changsha", focus_tags=["higher_education"]),
    org(id="scut", legal_name_zh="华南理工大学", legal_name_en="South China University of Technology",
        display_name_zh="华南理工大学", display_name_en="SCUT", organization_type="university",
        headquarters_city_id="guangzhou", focus_tags=["higher_education"]),
    org(id="cqu", legal_name_zh="重庆大学", legal_name_en="Chongqing University",
        display_name_zh="重庆大学", display_name_en="Chongqing University", organization_type="university",
        headquarters_city_id="chongqing", focus_tags=["higher_education"]),
    org(id="cqut", legal_name_zh="重庆理工大学", legal_name_en="Chongqing University of Technology",
        display_name_zh="重庆理工大学", display_name_en="CQUT", organization_type="university",
        headquarters_city_id="chongqing", focus_tags=["higher_education"]),
    org(id="autohome", legal_name_zh="汽车之家", legal_name_en="Autohome",
        display_name_zh="汽车之家", display_name_en="Autohome", organization_type="media_company",
        headquarters_city_id="beijing", website="https://www.autohome.com.cn/", focus_tags=["auto_media"],
        source_ids=srcs(SRC_MEDIA, SRC_BRIEF)),
    org(id="gasgoo", legal_name_zh="盖世汽车", legal_name_en="Gasgoo",
        display_name_zh="盖世汽车", display_name_en="Gasgoo", organization_type="media_company",
        headquarters_city_id="shanghai", website="https://www.gasgoo.com/", focus_tags=["auto_media"],
        source_ids=srcs(SRC_MEDIA, SRC_BRIEF)),
    org(id="garage42", legal_name_zh="42号车库", legal_name_en="Garage 42",
        display_name_zh="42号车库", display_name_en="Garage 42", organization_type="media_company",
        headquarters_city_id="shanghai", focus_tags=["auto_media"],
        source_ids=srcs(SRC_MEDIA, SRC_BRIEF)),
    org(id="xchuxing", legal_name_zh="新出行", legal_name_en="Xchuxing",
        display_name_zh="新出行", display_name_en="Xchuxing", organization_type="media_company",
        headquarters_city_id="shenzhen", focus_tags=["auto_media"],
        source_ids=srcs(SRC_MEDIA, SRC_BRIEF)),
    org(id="pcauto", legal_name_zh="太平洋汽车", legal_name_en="PCauto",
        display_name_zh="太平洋汽车", display_name_en="PCauto", organization_type="media_company",
        headquarters_city_id="guangzhou", website="https://www.pcauto.com.cn/", focus_tags=["auto_media"],
        source_ids=srcs(SRC_MEDIA, SRC_BRIEF)),
    org(id="gac-aion", legal_name_zh="广汽埃安新能源汽车股份有限公司", legal_name_en="GAC Aion New Energy Automobile Co., Ltd.",
        display_name_zh="广汽埃安", display_name_en="GAC Aion", organization_type="brand",
        parent_id="gac", headquarters_city_id="guangzhou", focus_tags=["oem_manufacturing"]),
    org(id="saic-vw", legal_name_zh="上汽大众汽车有限公司", legal_name_en="SAIC Volkswagen Automotive Co., Ltd.",
        display_name_zh="上汽大众", display_name_en="SAIC Volkswagen", organization_type="automaker",
        parent_id="saic", headquarters_city_id="shanghai", focus_tags=["oem_manufacturing"]),
    org(id="baic-foton", legal_name_zh="北汽福田汽车股份有限公司", legal_name_en="BAIC Foton Motor Co., Ltd.",
        display_name_zh="北汽福田", display_name_en="Foton", organization_type="automaker",
        parent_id="baic", headquarters_city_id="beijing", focus_tags=["oem_manufacturing"]),
    org(id="dongfeng-cv", legal_name_zh="东风商用车有限公司", legal_name_en="Dongfeng Commercial Vehicle Co., Ltd.",
        display_name_zh="东风商用车", display_name_en="Dongfeng Commercial Vehicles", organization_type="automaker",
        parent_id="dongfeng", headquarters_city_id="shiyan", focus_tags=["oem_manufacturing", "auto_history"]),
]

ORG_BY_ID = {o["id"]: o for o in ORGS}

FEATURED = {
    "beijing": ["baic", "beijing-benz", "xiaomi-auto", "li-auto", "baidu", "horizon-robotics", "tsinghua", "bit", "autohome"],
    "shanghai": ["saic", "tesla-china", "tongji", "sjtu", "gasgoo", "garage42", "saic-vw"],
    "shenzhen": ["byd", "xchuxing"],
    "guangzhou": ["gac", "gac-honda", "gac-toyota", "dongfeng-nissan", "xpeng", "weiride", "pony-ai", "scut", "pcauto", "gac-aion"],
    "chongqing": ["changan", "seres", "qianli", "caeri", "cqu", "cqut"],
    "hefei": ["jac", "nio", "vw-anhui", "byd", "changan", "gotion", "hfut"],
    "wuhu": ["chery"],
    "xian": ["byd", "geely", "changan-univ"],
    "changchun": ["faw", "hongqi", "jiefang", "bestune", "faw-vw", "audi-faw-nev", "jlu"],
    "zhengzhou": ["byd", "yutong", "zhengzhou-nissan", "saic"],
    "liuzhou": ["sgmw", "dongfeng-liuzhou", "guangxi-auto", "jiefang"],
    "wuhan": ["dongfeng", "voyah", "mengshi", "aeolus", "whut"],
    "changsha": ["byd", "saic-vw", "gac-aion", "baic-foton", "hnu"],
    "tianjin": ["faw-toyota", "faw-vw", "gwm", "catarc"],
    "chengdu": ["faw-vw", "faw-toyota", "volvo-cars-chengdu", "geely"],
    "ningde": ["catl"],
    "changzhou": ["li-auto", "byd", "catl", "svolt", "calb"],
    "suzhou": [],
    "ningbo": ["joyson", "tuopu", "minth", "huaxiang", "geely"],
    "huizhou": ["desay-sv", "holosonics", "eve-energy"],
    "yibin": ["catl"],
    "baoding": ["gwm"],
    "jinan": ["sinotruk", "byd", "geely"],
    "shiyan": ["dongfeng-cv"],
    "xiamen": ["king-long", "golden-dragon"],
}


def fac(**kw):
    city = next(c for c in CITIES if c["id"] == kw["city_id"])
    row = dict(
        district_zh=None, district_en=None, lat=city["lat"], lng=city["lng"],
        status="active", opened_at=None, current_products=[], technology_tags=[],
        last_verified=LV, confidence=0.62, source_ids=srcs(SRC_BRIEF),
        coord_note_zh="坐标暂用城市中心点，待工厂级地理编码。",
        coord_note_en="Coordinates currently use the city centroid pending plant-level geocoding.",
    )
    row.update(kw)
    return row


FACILITIES = [
    fac(id="tesla-shanghai-gigafactory", name_zh="特斯拉上海超级工厂", name_en="Tesla Shanghai Gigafactory",
        operator_id="tesla-china", city_id="shanghai", district_zh="临港", district_en="Lingang",
        facility_type="vehicle_plant", technology_tags=["nev"], current_products=["Model 3", "Model Y"]),
    fac(id="byd-shenzhen-hq", name_zh="比亚迪深圳总部及研发", name_en="BYD Shenzhen HQ & R&D",
        operator_id="byd", city_id="shenzhen", district_zh="坪山", district_en="Pingshan",
        facility_type="headquarters_campus", technology_tags=["nev", "battery"]),
    fac(id="byd-xian-plant", name_zh="比亚迪西安基地", name_en="BYD Xi'an base",
        operator_id="byd", city_id="xian", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="byd-hefei-plant", name_zh="比亚迪合肥基地", name_en="BYD Hefei base",
        operator_id="byd", city_id="hefei", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="byd-zhengzhou-plant", name_zh="比亚迪郑州基地", name_en="BYD Zhengzhou base",
        operator_id="byd", city_id="zhengzhou", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="byd-changsha-plant", name_zh="比亚迪长沙基地", name_en="BYD Changsha base",
        operator_id="byd", city_id="changsha", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="byd-jinan-plant", name_zh="比亚迪济南基地", name_en="BYD Jinan base",
        operator_id="byd", city_id="jinan", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="byd-changzhou-plant", name_zh="比亚迪常州基地", name_en="BYD Changzhou base",
        operator_id="byd", city_id="changzhou", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="chery-wuhu-plant", name_zh="奇瑞芜湖整车基地", name_en="Chery Wuhu vehicle base",
        operator_id="chery", city_id="wuhu", facility_type="vehicle_plant", technology_tags=["export"]),
    fac(id="faw-changchun-hq", name_zh="中国一汽长春总部", name_en="FAW Changchun headquarters",
        operator_id="faw", city_id="changchun", facility_type="headquarters_campus", technology_tags=["auto_history"]),
    fac(id="li-auto-changzhou", name_zh="理想汽车常州工厂", name_en="Li Auto Changzhou plant",
        operator_id="li-auto", city_id="changzhou", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="catl-ningde", name_zh="宁德时代宁德基地", name_en="CATL Ningde base",
        operator_id="catl", city_id="ningde", facility_type="battery_plant", technology_tags=["battery"]),
    fac(id="catl-yibin", name_zh="四川时代宜宾基地", name_en="CATL Sichuan Yibin base",
        operator_id="catl", city_id="yibin", facility_type="battery_plant", technology_tags=["battery"]),
    fac(id="gwm-xushui", name_zh="长城汽车徐水智慧工厂", name_en="GWM Xushui smart plant",
        operator_id="gwm", city_id="baoding", district_zh="徐水", district_en="Xushui",
        facility_type="vehicle_plant"),
    fac(id="sgmw-liuzhou", name_zh="上汽通用五菱柳州基地", name_en="SGMW Liuzhou base",
        operator_id="sgmw", city_id="liuzhou", facility_type="vehicle_plant"),
    fac(id="yutong-zhengzhou", name_zh="宇通客车郑州基地", name_en="Yutong Zhengzhou base",
        operator_id="yutong", city_id="zhengzhou", facility_type="vehicle_plant", technology_tags=["bus"]),
    fac(id="changan-chongqing", name_zh="长安汽车重庆整车基地", name_en="Changan Chongqing vehicle base",
        operator_id="changan", city_id="chongqing", facility_type="vehicle_plant"),
    fac(id="nio-hefei", name_zh="蔚来合肥制造基地", name_en="NIO Hefei manufacturing base",
        operator_id="nio", city_id="hefei", facility_type="vehicle_plant", technology_tags=["nev"]),
    fac(id="dongfeng-shiyan", name_zh="东风商用车十堰工厂", name_en="Dongfeng CV Shiyan plant",
        operator_id="dongfeng-cv", city_id="shiyan", facility_type="vehicle_plant", technology_tags=["commercial"]),
    fac(id="catarc-tianjin", name_zh="中汽中心天津检测基地", name_en="CATARC Tianjin testing campus",
        operator_id="catarc", city_id="tianjin", facility_type="testing_center", technology_tags=["testing"]),
]


def role(city_id, entity_id, role_type, zh, en):
    return dict(
        id=f"{city_id}__{entity_id}__{role_type}",
        city_id=city_id, entity_id=entity_id, role_type=role_type,
        description_zh=zh, description_en=en, source_ids=srcs(SRC_BRIEF),
    )


ROLES = []
for city_id, ids in FEATURED.items():
    for eid in ids:
        o = ORG_BY_ID.get(eid)
        if not o:
            continue
        rtype = "headquarters" if o.get("headquarters_city_id") == city_id else "factory"
        if o["organization_type"] == "university":
            rtype = "university_campus"
        elif o["organization_type"] == "media_company":
            rtype = "media_editorial_office"
        elif o["organization_type"] in ("testing_body", "research_institute"):
            rtype = "testing_center"
        elif o["organization_type"] in ("software_company", "chip_company") and o.get("headquarters_city_id") == city_id:
            rtype = "rd_center"
        elif o["organization_type"] in ("supplier", "battery_company") and o.get("headquarters_city_id") != city_id:
            rtype = "supplier_plant"
        ROLES.append(role(city_id, eid, rtype, f"{o['display_name_zh']}在{city_id}的{rtype}角色", f"{o['display_name_en']} {rtype} role in {city_id}"))

# Extra BYD multi-city manufacturing roles
for cid in ("xian", "hefei", "zhengzhou", "changsha", "jinan", "changzhou"):
    if not any(r["city_id"] == cid and r["entity_id"] == "byd" for r in ROLES):
        ROLES.append(role(cid, "byd", "factory", "比亚迪整车制造基地", "BYD vehicle manufacturing base"))
if not any(r["city_id"] == "shenzhen" and r["entity_id"] == "byd" and r["role_type"] == "rd_center" for r in ROLES):
    ROLES.append(role("shenzhen", "byd", "rd_center", "南山与坪山研发集群", "Nanshan and Pingshan R&D cluster"))

CLUSTERS = [
    dict(id="yangtze-river-delta", name_zh="长三角汽车网络", name_en="Yangtze River Delta auto network",
         city_ids=["shanghai", "suzhou", "changzhou", "ningbo", "hefei", "wuhu"],
         summary_zh="上海承担总部、芯片、软件、国际合作和整车制造；常州具有电池与新能源整车；苏州和宁波拥有汽车电子与零部件；合肥和芜湖承担快速增长的整车生产。完整链还应包含杭州，将在二期补入。",
         summary_en="Shanghai carries HQ, chips, software, international cooperation and vehicle plants; Changzhou batteries and NEVs; Suzhou and Ningbo electronics and parts; Hefei and Wuhu fast-growing vehicle output. Hangzhou joins in phase 2.",
         output_note_zh="国家发展改革委区域资料将上海软件芯片、常州动力电池和宁波整车制造作为协作案例。",
         output_note_en="NDRC regional materials cite Shanghai software/chips, Changzhou batteries and Ningbo vehicle manufacturing as a collaboration case."),
    dict(id="greater-bay-area", name_zh="粤港澳大湾区汽车网络", name_en="Greater Bay Area auto network",
         city_ids=["guangzhou", "shenzhen", "huizhou"],
         summary_zh="广州多品牌整车；深圳比亚迪总部、汽车电子和智能驾驶；惠州德赛西威、华阳和亿纬锂能。佛山、东莞将在二期补入。",
         summary_en="Guangzhou multi-brand plants; Shenzhen BYD HQ, electronics and autonomy; Huizhou Desay SV, HuaYang and EVE. Foshan and Dongguan join in phase 2.",
         output_note_zh="广州和深圳官方产业规划均将跨城市协作列为重要方向。",
         output_note_en="Guangzhou and Shenzhen official industry plans both treat cross-city collaboration as a priority."),
    dict(id="jingjinji", name_zh="京津冀汽车网络", name_en="Jing-Jin-Ji auto network",
         city_ids=["beijing", "tianjin", "baoding"],
         summary_zh="北京总部、算法、软件和创新平台；天津整车、检测标准和港口；保定长城总部和制造。廊坊等河北配套城市二期补入。",
         summary_en="Beijing HQ, algorithms, software and platforms; Tianjin vehicles, testing standards and port; Baoding GWM HQ and manufacturing. Langfang joins in phase 2.",
         output_note_zh="京津冀已形成以数小时运输半径组织的汽车供应链。",
         output_note_en="Jing-Jin-Ji already organises auto supply on a same-day trucking radius."),
    dict(id="chengyu", name_zh="成渝汽车网络", name_en="Chengdu–Chongqing auto network",
         city_ids=["chongqing", "chengdu", "yibin"],
         summary_zh="重庆与成都构成整车和零部件双中心，宜宾提供动力电池产业支持。",
         summary_en="Chongqing and Chengdu form a dual vehicle-and-parts centre; Yibin supplies power batteries.",
         output_note_zh="2024年成渝地区汽车产量约343万辆，新能源汽车约108.7万辆。",
         output_note_en="In 2024 the Chengdu–Chongqing region produced about 3.43 million vehicles, including about 1.087 million NEVs."),
    dict(id="hubei-axis", name_zh="湖北汽车轴线", name_en="Hubei auto axis",
         city_ids=["wuhan", "shiyan"],
         summary_zh="武汉侧重乘用车、新能源和智能网联；十堰侧重中重型商用车。襄阳、随州二期补入，适合做成东风历史专题。",
         summary_en="Wuhan: passenger cars, NEVs and intelligent connectivity; Shiyan: medium/heavy commercial vehicles. Xiangyang and Suizhou join in phase 2 as a Dongfeng history special.",
         output_note_zh=None, output_note_en=None),
    dict(id="hunan-axis", name_zh="湖南汽车轴线", name_en="Hunan auto axis",
         city_ids=["changsha"],
         summary_zh="长沙拥有比亚迪、广汽埃安和上汽大众。株洲新能源商用车和湘潭吉利体系二期补入。",
         summary_en="Changsha hosts BYD, GAC Aion and SAIC Volkswagen. Zhuzhou NEV commercial vehicles and Xiangtan's Geely system join in phase 2.",
         output_note_zh=None, output_note_en=None),
    dict(id="northeast", name_zh="东北一汽枢纽", name_en="Northeast FAW hub",
         city_ids=["changchun"],
         summary_zh="长春作为一汽总部与历史核心独立呈现，后续连接沈阳华晨宝马供应网络。",
         summary_en="Changchun is presented as FAW HQ and historical core; Shenyang BMW Brilliance supply joins later.",
         output_note_zh=None, output_note_en=None),
    dict(id="central-plains", name_zh="中原客车与新能源", name_en="Central Plains coaches and NEVs",
         city_ids=["zhengzhou"],
         summary_zh="郑州同时承担比亚迪综合制造和宇通全球客车影响力。",
         summary_en="Zhengzhou hosts both BYD integrated manufacturing and Yutong's global coach role.",
         output_note_zh=None, output_note_en=None),
    dict(id="guangxi", name_zh="桂中车城", name_en="Central Guangxi auto city",
         city_ids=["liuzhou"],
         summary_zh="柳州以五菱、柳汽和本地汽车文化构成相对完整的地方车城。",
         summary_en="Liuzhou forms a relatively complete local auto city around Wuling, Dongfeng Liuzhou Motor and civic auto culture.",
         output_note_zh=None, output_note_en=None),
    dict(id="battery-corridor", name_zh="动力电池走廊", name_en="Power-battery corridor",
         city_ids=["ningde", "changzhou", "yibin", "hefei", "huizhou"],
         summary_zh="宁德总部、常州集聚、宜宾能源条件、合肥国轩与整车、惠州亿纬，用来说明电池城市不必拥有整车厂。",
         summary_en="CATL HQ, Changzhou agglomeration, Yibin energy conditions, Hefei Gotion plus vehicles, Huizhou EVE — battery cities need not host OEM plants.",
         output_note_zh=None, output_note_en=None),
    dict(id="northwest", name_zh="西北制造节点", name_en="Northwest manufacturing node",
         city_ids=["xian"],
         summary_zh="西安以比亚迪大规模制造进入全国产量第一梯队。",
         summary_en="Xi'an entered the national output first tier through BYD-scale manufacturing.",
         output_note_zh=None, output_note_en=None),
    dict(id="shandong", name_zh="山东商用车与新能源", name_en="Shandong commercial vehicles and NEVs",
         city_ids=["jinan"],
         summary_zh="济南以重汽商用车叠加比亚迪、吉利新能源整车。青岛一汽-大众/解放/奇瑞将在二期补入。",
         summary_en="Jinan stacks Sinotruk commercial vehicles with BYD and Geely NEV plants. Qingdao FAW-VW/Jiefang/Chery joins in phase 2.",
         output_note_zh=None, output_note_en=None),
    dict(id="fujian-bus", name_zh="福建客车", name_en="Fujian coaches",
         city_ids=["xiamen"],
         summary_zh="厦门金龙与金旅代表客车和新能源商用车出口路径。",
         summary_en="Xiamen King Long and Golden Dragon represent the coach and NEV-commercial export path.",
         output_note_zh=None, output_note_en=None),
]

ADJACENT = [
    ("yangtze-river-delta", [("shanghai", "suzhou"), ("suzhou", "changzhou"), ("changzhou", "ningbo"), ("shanghai", "hefei"), ("hefei", "wuhu")]),
    ("greater-bay-area", [("guangzhou", "shenzhen"), ("shenzhen", "huizhou"), ("guangzhou", "huizhou")]),
    ("jingjinji", [("beijing", "tianjin"), ("beijing", "baoding"), ("tianjin", "baoding")]),
    ("chengyu", [("chongqing", "chengdu"), ("chengdu", "yibin"), ("chongqing", "yibin")]),
    ("hubei-axis", [("wuhan", "shiyan")]),
]


def rel(from_id, rtype, to_id, cluster_id=None, zh="", en=""):
    cid = cluster_id or ""
    return dict(
        id=f"{from_id}__{rtype}__{to_id}__{cid}",
        from_id=from_id, relation_type=rtype, to_id=to_id, cluster_id=cluster_id,
        description_zh=zh, description_en=en, source_ids=srcs(SRC_BRIEF),
    )


RELATIONS = []
for cl in CLUSTERS:
    for cid in cl["city_ids"]:
        RELATIONS.append(rel(cid, "belongs_to_cluster", cl["id"], cl["id"], "城市属于该产业集群", "City belongs to this cluster"))
for cl_id, pairs in ADJACENT:
    for a, b in pairs:
        RELATIONS.append(rel(a, "cluster_adjacent", b, cl_id, "产业集群相邻协作", "Adjacent collaboration inside the cluster"))
        RELATIONS.append(rel(b, "cluster_adjacent", a, cl_id, "产业集群相邻协作", "Adjacent collaboration inside the cluster"))
RELATIONS.append(rel("byd", "located_in", "shenzhen", None, "集团总部", "Group headquarters"))
RELATIONS.append(rel("catl", "located_in", "ningde", None, "集团总部", "Group headquarters"))
RELATIONS.append(rel("faw", "historically_linked_to", "changchun", None, "一汽发源地", "FAW place of origin"))
RELATIONS.append(rel("dongfeng", "historically_linked_to", "shiyan", None, "二汽发源地", "Second Auto Works place of origin"))

STATS = []
OUTPUT_2025 = {
    "chongqing": 2787700, "guangzhou": 2409600, "hefei": 1872000, "wuhu": 1830000,
    "shanghai": 1772000, "xian": 1482700, "beijing": 1467100, "changchun": 1461300,
    "zhengzhou": 1205000, "liuzhou": 1151900,
}
NEV_2025 = {"hefei": 1371000, "xian": 1051400}
for cid, total in OUTPUT_2025.items():
    STATS.append(dict(
        city_id=cid, year=2025, total_vehicle_output=total,
        nev_output=NEV_2025.get(cid), commercial_vehicle_output=None, passenger_vehicle_output=None,
        statistical_scope="local_compilation_actual_production_city",
        scope_note_zh="地方统计资料拼合，按车辆实际生产所在地归属；口径可能含全市/经开区/规模以上差异，并非国家统计局发布的统一城市排行。",
        scope_note_en="Compiled from local statistical releases attributed to actual production location. Scopes may mix city / development-zone / above-scale industry. Not a unified NBS city ranking.",
        source_ids=srcs(SRC_COMP), confidence=0.58,
    ))
# Qingdao is in the compiled ranking but not a V1 city card — recorded as a note source only.

MEDIA = [
    dict(id="media-autohome", organization_id="autohome", media_name_zh="汽车之家", media_name_en="Autohome",
         media_type="portal", operating_company_zh="汽车之家", operating_company_en="Autohome",
         registered_city_id="beijing", editorial_city_id="beijing", founded_year=2005,
         focus_tags=["portal"], website="https://www.autohome.com.cn/", status="active",
         last_verified=LV, confidence=0.8, source_ids=srcs(SRC_MEDIA), national_platform=True),
    dict(id="media-gasgoo", organization_id="gasgoo", media_name_zh="盖世汽车", media_name_en="Gasgoo",
         media_type="trade_media", operating_company_zh="盖世汽车", operating_company_en="Gasgoo",
         registered_city_id="shanghai", editorial_city_id="shanghai", founded_year=None,
         focus_tags=["trade_media"], website="https://www.gasgoo.com/", status="active",
         last_verified=LV, confidence=0.75, source_ids=srcs(SRC_MEDIA), national_platform=True),
    dict(id="media-garage42", organization_id="garage42", media_name_zh="42号车库", media_name_en="Garage 42",
         media_type="nev_media", operating_company_zh="42号车库", operating_company_en="Garage 42",
         registered_city_id="shanghai", editorial_city_id="shanghai", founded_year=None,
         focus_tags=["nev_media"], website=None, status="active",
         last_verified=LV, confidence=0.7, source_ids=srcs(SRC_MEDIA), national_platform=True),
    dict(id="media-xchuxing", organization_id="xchuxing", media_name_zh="新出行", media_name_en="Xchuxing",
         media_type="nev_media", operating_company_zh="新出行", operating_company_en="Xchuxing",
         registered_city_id="shenzhen", editorial_city_id="shenzhen", founded_year=None,
         focus_tags=["nev_media"], website=None, status="active",
         last_verified=LV, confidence=0.72, source_ids=srcs(SRC_MEDIA), national_platform=True),
    dict(id="media-pcauto", organization_id="pcauto", media_name_zh="太平洋汽车", media_name_en="PCauto",
         media_type="portal", operating_company_zh="太平洋汽车", operating_company_en="PCauto",
         registered_city_id="guangzhou", editorial_city_id="guangzhou", founded_year=None,
         focus_tags=["portal"], website="https://www.pcauto.com.cn/", status="active",
         last_verified=LV, confidence=0.75, source_ids=srcs(SRC_MEDIA), national_platform=True),
]

INSTITUTIONS = [
    dict(id="inst-tsinghua", organization_id="tsinghua", school_zh="清华大学", school_en="Tsinghua University",
         city_id="beijing", college_zh="车辆与运载学院", college_en="School of Vehicle and Mobility",
         strengths_zh="新能源、智能驾驶、跨学科研究", strengths_en="NEV, autonomous driving, cross-disciplinary research",
         industry_partners=[], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-bit", organization_id="bit", school_zh="北京理工大学", school_en="Beijing Institute of Technology",
         city_id="beijing", college_zh="机械与车辆学院", college_en="School of Mechanical Engineering",
         strengths_zh="车辆工程与军工车辆传统", strengths_en="Vehicle engineering and defence-vehicle tradition",
         industry_partners=[], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-tongji", organization_id="tongji", school_zh="同济大学", school_en="Tongji University",
         city_id="shanghai", college_zh="汽车学院", college_en="School of Automotive Studies",
         strengths_zh="汽车工程、测试与国际合作", strengths_en="Automotive engineering, testing and international cooperation",
         industry_partners=["saic"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-sjtu", organization_id="sjtu", school_zh="上海交通大学", school_en="Shanghai Jiao Tong University",
         city_id="shanghai", college_zh="汽车动力与智能控制相关研究机构", college_en="Automotive power and intelligent-control labs",
         strengths_zh="动力系统与控制", strengths_en="Powertrain and control",
         industry_partners=[], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-jlu", organization_id="jlu", school_zh="吉林大学", school_en="Jilin University",
         city_id="changchun", college_zh="汽车工程学院", college_en="College of Automotive Engineering",
         strengths_zh="传统车辆工程积累深厚", strengths_en="Deep traditional vehicle-engineering stock",
         industry_partners=["faw"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-whut", organization_id="whut", school_zh="武汉理工大学", school_en="Wuhan University of Technology",
         city_id="wuhan", college_zh="汽车工程学院", college_en="School of Automotive Engineering",
         strengths_zh="传统车辆工程", strengths_en="Traditional vehicle engineering",
         industry_partners=["dongfeng"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-hfut", organization_id="hfut", school_zh="合肥工业大学", school_en="Hefei University of Technology",
         city_id="hefei", college_zh="汽车与交通工程学院", college_en="School of Automotive and Transportation Engineering",
         strengths_zh="传统车辆工程", strengths_en="Traditional vehicle engineering",
         industry_partners=["jac"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-chd", organization_id="changan-univ", school_zh="长安大学", school_en="Chang'an University",
         city_id="xian", college_zh="汽车学院", college_en="School of Automobile",
         strengths_zh="传统车辆工程", strengths_en="Traditional vehicle engineering",
         industry_partners=[], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-hnu", organization_id="hnu", school_zh="湖南大学", school_en="Hunan University",
         city_id="changsha", college_zh="车辆工程及智能汽车研究", college_en="Vehicle engineering and intelligent-vehicle research",
         strengths_zh="车辆工程与智能汽车", strengths_en="Vehicle engineering and intelligent vehicles",
         industry_partners=[], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-scut", organization_id="scut", school_zh="华南理工大学", school_en="South China University of Technology",
         city_id="guangzhou", college_zh="车辆工程相关院系", college_en="Vehicle-engineering departments",
         strengths_zh="车辆工程", strengths_en="Vehicle engineering",
         industry_partners=["gac"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-cqu", organization_id="cqu", school_zh="重庆大学", school_en="Chongqing University",
         city_id="chongqing", college_zh="车辆工程相关学院", college_en="Vehicle-engineering schools",
         strengths_zh="车辆工程", strengths_en="Vehicle engineering",
         industry_partners=["changan"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
    dict(id="inst-cqut", organization_id="cqut", school_zh="重庆理工大学", school_en="Chongqing University of Technology",
         city_id="chongqing", college_zh="车辆工程相关学院", college_en="Vehicle-engineering schools",
         strengths_zh="车辆工程", strengths_en="Vehicle engineering",
         industry_partners=["changan"], last_verified=LV, source_ids=srcs(SRC_BRIEF)),
]

SOURCES = [
    dict(id=SRC_COMP, publisher_zh="地方统计资料汇编（非国家统一排行）", publisher_en="Compilation of local statistical releases (not a unified national ranking)",
         title_zh="2025年主要汽车生产城市产量拼合", title_en="2025 vehicle-output figures compiled from local releases",
         source_type="compilation", grade="C", published_at="2026-08", accessed_at="2026-08-18", fact_date="2025",
         url=None, confidence=0.6,
         notes_zh="重庆278.77万、广州240.96万、合肥187.20万、芜湖183.00万、上海177.20万、西安148.27万、北京146.71万、长春146.13万、郑州120.50万、柳州115.19万、青岛102.20万（青岛城市卡二期）。合肥新能源汽车约137.1万，西安约105.14万。",
         notes_en="Chongqing 2.7877M, Guangzhou 2.4096M, Hefei 1.8720M, Wuhu 1.8300M, Shanghai 1.7720M, Xi'an 1.4827M, Beijing 1.4671M, Changchun 1.4613M, Zhengzhou 1.2050M, Liuzhou 1.1519M, Qingdao 1.0220M (Qingdao city card in phase 2). Hefei NEV ~1.371M; Xi'an NEV ~1.0514M."),
    dict(id=SRC_BRIEF, publisher_zh="QROST 研究简报", publisher_en="QROST research brief",
         title_zh="中国汽车城市图谱第一轮调研结论", title_en="China auto-city atlas, first research pass",
         source_type="compilation", grade="C", published_at="2026-08-18", accessed_at="2026-08-18", fact_date="2026-08",
         url=None, confidence=0.65,
         notes_zh="城市角色、企业名单、产业集群与媒体所在地的结构化整理。产能、在产车型和工厂状态需后续用A/B级来源逐条核验。",
         notes_en="Structured roles, rosters, clusters and media locations. Plant status, capacity and nameplates still need A/B-grade verification."),
    dict(id=SRC_YRD, publisher_zh="国家发展和改革委员会（区域协作资料，待补URL）", publisher_en="NDRC regional collaboration materials (URL pending)",
         title_zh="长三角软件芯片 / 常州电池 / 宁波整车协作案例", title_en="YRD case: Shanghai software/chips, Changzhou batteries, Ningbo vehicles",
         source_type="government_stats", grade="B", published_at=None, accessed_at="2026-08-18", fact_date=None,
         url=None, confidence=0.55,
         notes_zh="调研引用国家发展改革委区域资料，具体公文URL待下一轮补链。",
         notes_en="Cited from NDRC regional materials; exact document URL to be attached next pass."),
    dict(id=SRC_CHENGYU, publisher_zh="成渝地区产业统计（待补URL）", publisher_en="Chengdu–Chongqing regional industry statistics (URL pending)",
         title_zh="2024年成渝汽车产量约343万辆、新能源汽车约108.7万辆", title_en="2024 Chengyu vehicle output ~3.43M, NEV ~1.087M",
         source_type="government_stats", grade="B", published_at="2025", accessed_at="2026-08-18", fact_date="2024",
         url=None, confidence=0.55,
         notes_zh="区域合计，不是单座城市产量。URL待补。",
         notes_en="Regional aggregate, not a single-city series. URL pending."),
    dict(id=SRC_MEDIA, publisher_zh="各媒体公开联系地址", publisher_en="Public contact addresses of each outlet",
         title_zh="汽车之家北京；盖世/42号车库上海；新出行深圳南山；太平洋汽车广州", title_en="Autohome Beijing; Gasgoo/Garage42 Shanghai; Xchuxing Shenzhen Nanshan; PCauto Guangzhou",
         source_type="company_site", grade="B", published_at=None, accessed_at="2026-08-18", fact_date="2026-08",
         url=None, confidence=0.7,
         notes_zh="运营公司注册地、编辑团队所在地和主要业务城市可能不同。易车、懂车帝等全国性平台尚未核验归属。",
         notes_en="Registered office, editorial team and business city can diverge. National platforms such as Bitauto and Dongchedi are not yet assigned."),
]


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    for c in CITIES:
        c["featured_entity_ids"] = [eid for eid in FEATURED.get(c["id"], []) if eid in ORG_BY_ID]

    dump("cities.json", {"cities": CITIES})
    dump("organizations.json", {"organizations": ORGS})
    dump("facilities.json", {"facilities": FACILITIES})
    dump("city-roles.json", {"city_roles": ROLES})
    dump("relations.json", {"relations": RELATIONS})
    dump("clusters.json", {"clusters": CLUSTERS})
    dump("statistics.json", {"statistics": STATS})
    dump("media.json", {"media": MEDIA})
    dump("institutions.json", {"institutions": INSTITUTIONS})
    dump("sources.json", {"sources": SOURCES})

    counts = {
        "cities": len(CITIES),
        "organizations": len(ORGS),
        "facilities": len(FACILITIES),
        "city_roles": len(ROLES),
        "relations": len(RELATIONS),
        "clusters": len(CLUSTERS),
        "statistics": len(STATS),
        "media": len(MEDIA),
        "institutions": len(INSTITUTIONS),
        "sources": len(SOURCES),
        "core_cities": sum(1 for c in CITIES if c["tier"] == "core"),
        "specialist_cities": sum(1 for c in CITIES if c["tier"] == "specialist"),
    }
    dump("manifest.json", {
        "data_version": "v1-2026-08",
        "generated_at": "2026-08-19",
        "last_verified": LV,
        "counts": counts,
        "notes_zh": "V1：15座核心城 + 10座专业城。产量为地方统计拼合。",
        "notes_en": "V1: 15 core + 10 specialist cities. Output figures are a local-statistics compilation.",
    })
    print("seed counts:", counts)


if __name__ == "__main__":
    main()
